### PR TITLE
React Content Query WebPart

### PR DESCRIPTION
**Pull request by spplante**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | n/a
#### What's in this Pull Request?

Added the samples/react-content-query-webpart : 

_The React Content Query WebPart is a modern version of the good old Content by Query WebPart that was introduced in SharePoint 2007. Built for SharePoint 2016 and Office 365, this modern version is built against the new SharePoint Framework (SPFx) and uses the latest Web Stack practices. While the original WebPart was based on a XSLT templating engine, this React WebPart is based on the well known Handlebars templating engine, which empowers users to create simple, yet powerfull HTML templates for rendering the queried content. This new version also lets the user query any site collections which resides on the same domain url, add unlimited filters, query DateTime fields to the nearest minute rather than being limited to a day, and much more._

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx Simon-Pierre, this is a really cool sample and extremely powerful web part. Would you have a chance to demonstrate this in one of our community calls, for example in the SPFx SIG call on 17th of August? Would be great to get a demo and code walkthrough recorded and shared through PnP YouTube channel, if that works for you.

**Comment by spplante** [comment]
Thanks Vesa, that would be awesome, can you send me the details about that community call to sp.plante@gmail.com? Thanks!

**Comment by VesaJuvonen** [comment]
Actually Simon, would you be available for 10-15 min demo already in tomorrow's monthly community call at 8 AM PT? - This is also recorded and pushed out to our YouTube channel. I know that it's on short notice, so absolutely understand if you prefer 17th, but we would have a spot for a demo, so wanted to check your availability.

**Comment by spplante** [comment]
Sure, I would be ok with a quick demo tomorrow 8AM PT (11h00 AM for Montreal). Send me the details and I will work something out tonight!

**Comment by VesaJuvonen** [comment]
thx - you can download monthly community call invite for following location - http://aka.ms/sppnp-call. We'll promote you as a presenter when you join. We'll first cover the recent updates around SP Dev ecosystem and then move to misc demos. You'll be one of the demo presenters. I'll get you updated as a presenter also on our monthly communications, which will go live later today from http://dev.office.com/blogs.

**Comment by spplante** [comment]
Sounds good!

**Comment by VesaJuvonen** [comment]
thx Simon for the demo you did. One thing to update actually in your code, since got also internally questions (engineering leads) around who has written this. Seems that you skipped the author information in the readme and would definitely like to see that included there, so that people would know who has actually done the implementations. Following is in the default readme template, but it was not in your readme. 

Solution | Author(s)
-- | --
folder name | Author details

**Comment by spplante** [comment]
My bad, I will add this right now, thanks Vesa

**Comment by spplante** [comment]
Done, I added the following pull request which adds the author to the read me : 

https://github.com/SharePoint/sp-dev-fx-webparts/pull/283

**Pull request merged**
