### PR TITLE
Basic Site Provisioning using SharePoint Framework client-side web part and Microsoft Bot Framework

### PR DESCRIPTION
**Pull request by sprider**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | n/a

#### What's in this Pull Request?

Sample SharePoint Framework client-side web part illustrating Site Provisioning using Microsoft Bot Framework.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Joseph, sorry for small delay on this, but absolutely in our radar to get processed asap. Looks really good.

**Comment by VesaJuvonen** [comment]
thx Joseph, great sample and good to have the bot web chat integration demonstrated this ways as well, since native web chat from the bot framework supports some nice capabilities. Great sample. If you have availability, this would be a great sample to demonstrate on the January monthly community call on Tuesday 10th of January at 8 AM PST. Let me know, if you're interested and available. thx.

**Comment by sprider** [comment]
Thank you Vesa. I am excited to present this in our next community call. Thank you for this opportunity.

**Comment by VesaJuvonen** [comment]
thx Joseph, looking forward. I'll get your spot shared in the monthly community call agenda in our communications. Looking forward for this and thx for the great sample. You most likely have the invite for this already, but you can download the invite from http://aka.ms/sppnp-call. Next one is on Tuesday 10th of January at 8 AM - won't be sending any other invites for this, which is hopefully good. Your demo spot is somewhere between 8:30 AM and 9:00 AM with around 15 minutes time for the functionality demo. That's always short, but hopefully doable. Thx for volunteering.

**Comment by sprider** [comment]
Sure, Vesa. Thank you for the update.

**Comment by VesaJuvonen** [comment]
Hi Joseph, here's published agenda for tomorrow's call with you now assigned on the sample demo. Hopefully demo or network gods are with us tomorrow, but should be good. Thx for volunteering on doing the demo and looking forward on seeing this sample live and the feedback.

**Comment by sprider** [comment]
Thank you Vesa

**Pull request merged**
