### PR TITLE
Js advanced commenting

### PR DESCRIPTION
**Pull request by sudharsank**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | no |

## What's in this Pull Request?

> A new component developed for advanced commenting.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
nice work @sudharsank. Would you be interested on doing a live demo of this in any of the upcoming community calls? We would have next free spot on 12th of March SPFx community call to demonstrate the feature and share your learnings.

**Comment by sudharsank** [comment]
@VesaJuvonen. Sure i look forward to do the demo. May i know is there any requirement to be sent for the demo?

**Comment by VesaJuvonen** [comment]
Hi Sudharshank - sorry for the delay here. Please confirm is you are still fine for the 12th of March demo. There's no expectation as such, but would prep 10-15 min with following plan

- Slide explaining who you are
- Slide explaining what you will show
- Showing the end user experience of the web part
- Showing key pieces of the code
- Slide on any learnings - what worked and what didn't work

Works?

**Comment by sudharsank** [comment]
Hi @VesaJuvonen, No probs. I am happy to do the demo on March 12th. I will start preparing the slides based on your requirement. Thanks for the opportunity.

**Comment by VesaJuvonen** [comment]
Thank you for confirming. Looking forward.

**Comment by VesaJuvonen** [comment]
Please note that due the daylight savings time changes in US (summer time) - call is one hour earlier today than normally... which is reflected in the recurrent meeting invite https://aka.ms/spdev-spfx-call.

**Pull request merged**
