### PR TITLE
New sample - SPFx React Textbox.io rich text editor integration 

### PR DESCRIPTION
**Pull request by FranckyC**
| Q               | A
| --------------- | ---
| New sample?      | yes

#### What's in this Pull Request?

This sample Web Part allows contributors to create rich text content in modern SharePoint pages using the third party Textbox.io editor.
The Texbox.io editor is a free web rich text editor (https://textbox.io/) offering much more content edition features than the original OOTB SharePoint Web Part (a CKEditor based subset with custom toolbar) to build dynamic pages (like Microsoft Word copy/paste).

### CODE REVIEW

**Comment by FranckyC** [comment]
@VesaJuvonen Validated, can be merged.

**Comment by VesaJuvonen** [comment]
Thx Francky, great work on these both. Super cool demos to show the possibilities of the platform. We should definitely do a demo of them both in the next SPFx community call if that works for you. Would be on 9th of Nov.

**Comment by FranckyC** [comment]
@VesaJuvonen  Yes sure, Nov 9th is ok for me. This sample is pretty simple so I don't think I will need 15 minutes. Only 5-10 would be sufficient.

**Comment by VesaJuvonen** [comment]
No rush - better to show the capability and some code - no way it's going to be less than 10 min.  :-)

**Comment by FranckyC** [comment]
@VesaJuvonen  haha you're right ;)

**Pull request merged**
