### PR TITLE
react-textboxio - (bug fix) fixed bug with display mode

### PR DESCRIPTION
**Pull request by FranckyC**
| Q               | A
| --------------- | ---
| Bug fix?        | yes

Fixed a bug regarding the editor behavior in display mode.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @FranckyC, appreciated. Sorry for the small delay.

**Comment by FranckyC** [comment]
@VesaJuvonen Thks!

**Comment by clechner77** [comment]
Pretty sure image uploads aren't implemented, so it's not a bug.  You'd need to add your own handler.  That said, when in displaymode it still throws a "can't read property 'getAttribute' of null when trying to find the element.

**Comment by FranckyC** [comment]
@pkrsingh86 @clechner77 is right, you need to implement the upload feature [by yourself](https://docs.ephox.com/display/tbio/upload). I've submitted an other [PR](https://github.com/SharePoint/sp-dev-fx-webparts/pull/389) to fix the display mode issue. Everything would be fine now. Let me know.

**Comment by pkrsingh86** [comment]
Sorry my Mistake. I have implemented this.

**Comment by FranckyC** [comment]
@pkrsingh86 Nice! Do you want to share this update by making a new PR  for this sample;)?

**Pull request merged**
