### PR TITLE
React my teams

### PR DESCRIPTION
**Pull request by joelfmrodrigues**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                                |
| New sample?     | yes                               |
| Related issues? | no |

## What's in this Pull Request?

New sample that uses MS Graph to list all the teams the current user is a member of.
Open the team default channel in the browser or client app.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @joelfmrodrigues - a nice simple demo showing few important concepts... would you be available for a community call demo around this... it's a repeat from the overall process perspective, but no harm doing a clean setup and demo the following:

- Show code 
- Show where did you solve the Graph API - documentation
- Show deployment - call out the permission message in app catalog
- Approve permissions in admin
- Show functioning in SharePoint page
- Talk about the open in client option etc.

Technically we have covered above pointers, but there's definitely no harm for repeating how simple and nice the overall process is. Works?

**Comment by joelfmrodrigues** [comment]
Hi Vesa, sure.
Let me know when there is an available slot

**Comment by VesaJuvonen** [comment]
Hi @joelfmrodrigues, we would have a spot for 28th of March call or then for the next one on the 11th of April. Either one works currently. Let me know what works for you. Thx.

**Comment by joelfmrodrigues** [comment]
Hi @VesaJuvonen 11th of April please 😊
Thanks

**Comment by VesaJuvonen** [comment]
thx @joelfmrodrigues - just confirming the 11th of April. See you there.

**Comment by VesaJuvonen** [comment]
Hi @joelfmrodrigues - just a reminder on the demo tomorrow - agenda goes now out using SharePoint account...

**Pull request merged**
