### PR TITLE
added react-ioc-tests sample web part

### PR DESCRIPTION
**Pull request by paulryan**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | no                               |
| New sample?     | yes                          |
| Related issues? | no |

## What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
This PR introduces a sample SPFx project: react-ioc-tests. This sample is not intended to be used directly for a functional purpose, but is instead a template for developing SPFx web parts using an IoC pattern. 

FROM THE README:

This web part is provided as an example of implementing an IoC (Inversion of Control) pattern in the context of a SharePoint Framework web part.

Following this pattern greatly improves the modularity, maintainability, and testability of the code.

The example includes 100% test coverage, using Jest and Enzyme, of .ts and .tsx files, excluding *WebPart.ts files. A dependency injector class specific to a web part class is used to map web part properties to component properties and create dependencies. This pattern is designed to remove logic from the *WebPart.ts file, the only ts file that isn't unit tested, and hence ensure that all relevant web part logic is tested.

Included in the coverage is a cache and logger class, along with a service class that fetches data asychronously using @PnP/sp and dynamic bundling.

The example also includes a pipeline definition .yaml file for Azure DevOps CI build pipeline (/pipelines/) which includes the build, running tests, and posting the test coverage results.

## Guidance

> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
> 
> *Please target your PR to `dev` branch. Released documents are in `master` branch.*
>

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx @paulryan. Would you be interested in doing a live demo of this sample in any of the upcoming SPFx community calls? The objective would be to cover the pattern and shown concepts on this one.

**Comment by paulryan** [comment]
@VesaJuvonen Yes, I would be happy to, thanks. Please email me some options and I'll see when I'm free.

**Comment by VesaJuvonen** [comment]
Hi @paulryan - we would have 10-15 min spot at the 9th of May call or then alternatively 23rd of May. Calls are at 7 AM PST. Would either one of those work for you?

**Comment by paulryan** [comment]
Hi Vesa, I’ll be busy at SP NA for the 23rd however the 9th of May call would be great, thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
