### PR TITLE
[react-search-refiners] 2.3.0.0 - Added result types feature + bug fixes

### PR DESCRIPTION
**Pull request by FranckyC**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                             |
| New feature?    | yes                               |
| New sample?     | no - yes?                               |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?

* Added result types feature with handlebars partials and PnP controls
* Miscellaneous bug fixes & improvements

### CODE REVIEW

**Comment by FranckyC** [comment]
@wobba If you have time to test this one.

**Comment by wobba** [comment]
@FranckyC @estruyf is releasing a beta version of spfx-controls-react we can update to so that both pnp control libs use 5.131.0.

When building the solution it seems the `brace` lib is included in the main web part even though prop pane is bundled separately. Do you know if it's referenced from something else than `TextDialog.tsx` in some weird way?

**Comment by wobba** [comment]
@FranckyC You need to dynamically load `PropertyFieldCodeEditor`, and can we use this instead of the direct dep on react-ace and TextDialog? So as to have one version of the code editor to deal with.

**Comment by wobba** [comment]
First off, thank you @estruyf for the help on my bundle issue and control loading 👍 

@FranckyC 

You can update to @pnp 1.2.7, and fix the below and bundle size should be ok. If you can replace TextDialog.tsx with the property control that would be cool as well, but not needed.

`package.json`
```
"@pnp/spfx-controls-react": "1.11.0-beta.ca4bd7e"
"react-ace": "5.8.0"
```

`SearchResultsWebPart.ts`
Remove import and replace with the code below, and replace references to the global vars.

```typescript
private _propertyFieldCodeEditor = null;
private _propertyFieldCodeEditorLanguages = null;
...
protected async loadPropertyPaneResources(): Promise<void> {

        // Code editor component for result types
        this._textDialogComponent = await import(
            /* webpackChunkName: 'search-property-pane' */
            '../controls/TextDialog'
        );
        const { PropertyFieldCodeEditor, PropertyFieldCodeEditorLanguages } = await import (
            /* webpackChunkName: 'search-property-pane' */
            '@pnp/spfx-property-controls/lib/PropertyFieldCodeEditor'
          );

        this._propertyFieldCodeEditor = PropertyFieldCodeEditor;
        this._propertyFieldCodeEditorLanguages = PropertyFieldCodeEditorLanguages;
    }

**Comment by FranckyC** [comment]
Thanks @wobba. I'll do the update asap.

**Comment by wobba** [comment]
@FranckyC looks good :) For new changes, create a new branch as to have a shorter commit log on the PR - not that it matters too much.

**Pull request merged**
