### PR TITLE
React teams tab suggested members

### PR DESCRIPTION
**Pull request by luismanez**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | yes                               |

## What's in this Pull Request?

New spfx webpart sample, based in 1.7 version, so it works as a Teams tab too. Webpart uses Graph API to suggest people to add to the Group / Teams, and allows you to select those members and add them to the group.
See readme file for more details.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Really cool stuff. Would you be interested in doing a demo on this in the community call?

**Comment by luismanez** [comment]
Yeah, sure! When would it be? This Thursday 22nd?

**Comment by VesaJuvonen** [comment]
Actually, we do have a sport free in this week as well. We will most likely have a slightly smaller audience as it's Thanksgiving in US, but the session is getting recorded for them. If that would work, let me know.

**Comment by VesaJuvonen** [comment]
Thx Luis, I'll get you on the 20th of Dec call. That works fine for us as well. You've been added on the agenda which will be pushed to the community during the week of the call. Thx.

**Comment by luismanez** [comment]
20th Dec, noted!! Thanks Vesa.

**Comment by VesaJuvonen** [comment]
Just a reminder on this. Agenda goes live in next hour using SharePoint twitter account.

**Comment by luismanez** [comment]
Are you trying it in Teams website, or the client App ? it doesn't work in the client app (first you have to enable Dev preview in the client app, but even with that, it doesn't work, but is because spfx Teams tab is still in preview). In MS Teams website it should work. I did my demo in the community call with the App installed in MS Teams website and worked fine. Other thing to try is just re-install the package...

**Comment by ValerasNarbutas** [comment]
hey, thanks for response, i did try on both, client and web, 
Web does show error "Manifest could not be found", could it be because of the sharepoint framework version you are using? I have noticed it is almost newest version.

**Comment by ValerasNarbutas** [comment]
I have reinstalled package, also downgraded node to version 8.15 but still same issue :(

**Pull request merged**
