### PR TITLE
React - My Tasks web part

### PR DESCRIPTION
**Pull request by joaojmendes**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no -                             |
| New feature?    | no                           |
| New sample?     | yes                              |

## What's in this Pull Request?

> New Sample - React My Tasks web part. Manage Planner Tasks in SharePoint.

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Hi João!

Thank you for contributing this awesome sample! :)

Would you be interested in doing a community call demo about it? Approximately 10 minutes long.  We still have room in the last SPFx call of the year on Thursday the 19th of December; would that work for you?

Cheers!

Laura

**Comment by joaojmendes** [comment]
Hi Laura 😊

Thank you so much 😊.

Glad to contribute to this great community, I haven't had much time to work in the community as I wished ...

This web part is my favorite web part of all the ones I've developed so far - it was a great design and implementation experience,

December 19th is my last working day before Christmas break, that's fine with me, but if something comes up, I'll let you know.

Have a nice day!

João.

**Comment by LauraKokkarinen** [comment]
Excellent, thank you! :)

Laura

**Comment by joaojmendes** [comment]
Hello laura,

I'm sorry, but I can't attend December 19 at the SIG call for the demonstration for professional reasons.

I'm sorry for the inconvenience.

In January maybe I have some time ...

Thank you!
João

**Comment by LauraKokkarinen** [comment]
Hi @joaojmendes ,

No worries! December is such a busy time for all of us so I completely understand.

Would the 16th of January sound good to you?

Laura

**Pull request merged**
