### PR TITLE
React Image Slider From Photo Gallery - Taxonomy Filter

### PR DESCRIPTION
**Pull request by sudhir007rawat**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | No                               |
| New feature?    | No                         |
| New sample?     | Yes                               |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?
This web part displays the image in slider based on the filter of Taxonomy from Property panel. Images are stored in PhotoGallery and tagged with Taxonomy. This web part showcases 3 important implementations.

1 - How to add the Terms in the property pane and pass the values to react component
2 - How to filter the list based on Taxonomy and extract the Image URL
3 - Implementation of Slick Slider

### CODE REVIEW

**Comment by sudhir007rawat** [comment]
test

**Comment by sudhir007rawat** [comment]
Q	A
Bug fix?	No
New feature?	No
New sample?	 Yes
Related issues?	fixes #X, partially #Y, mentioned in #Z
## What's in this Pull Request?
> New Sample added for review

**Comment by VesaJuvonen** [comment]
thx @sudhir007rawat, nice demo on important topics. Would you be available for doing a live demo on this in any of the upcoming SPFx community calls? Also - would definitely suggest updating your GitHub profile with at least a reference to your actual name, so that we can call you a contributor in the monthly messaging from the dev blog.

**Comment by sudhir007rawat** [comment]
Sure Vesa, love to give the demo on this. I have also updated my Github profile, Thanks for pointing out.

**Comment by VesaJuvonen** [comment]
Hi @sudhir007rawat, we would have a next free demo spot in 11th of April SPFx call - I know that it's a while, but hopefully works. Let me know what works for you. Thx.

**Comment by sudhir007rawat** [comment]
Sure, I will be available for 11th April. Do you know what will be the time
of the call?

**Comment by VesaJuvonen** [comment]
Hi @sudhir007rawat - unfortunately we would need to postpone this for 25th of April if that works for you? You can download recurrent invites for the SharePoint PnP calls from http://aka.ms/sppnp.

**Comment by sudhir007rawat** [comment]
Thanks, Vesa, sure I am fine with 25th April.

**Pull request merged**
