### PR TITLE
New Sample : React Graph Calendar

### PR DESCRIPTION
**Pull request by sebastienlevert**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | No                               |
| New feature?    | No                               |
| New sample?     | Yes                               |
| Related issues? | N/A |

## What's in this Pull Request?

This is a sample web part developed using React Framework to gather events from the underlying group calendar of a Team site. This sample also demonstrates the utilization of web parts as Teams tabs and offering a visualization context to change behaviors based on the platform used (Getting the proper information from the team vs. SharePoint site, understanding the context of the theme on Teams, etc.).

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Awesome, thx @sebastienlevert. Would you be interested on doing a live demo of this sample in any of the upcoming community calls? We would have currently still open spots for following calls:

- 2nd of January - coming soon - I know
- 30th of January

**Comment by sebastienlevert** [comment]
Definitely can do the 2nd! Let me know, I'm happy to demo this 😄

**Comment by VesaJuvonen** [comment]
I pushed out one version of agenda already out today, but more than happy to replace my 1.10 preview set to you demo for Thursday, if that works for you.

Let me know as a final confirmation asap, so will change the agenda promos for SharePoint and OfficeDev accounts which will go out on 1st. Thanks for volunteering and confirming.

**Comment by VesaJuvonen** [comment]
To avoid changes on the communicated agenda, let's skip the 2nd and then schedule for the next ones - we would have spots on the 30th of Jan and on the 13th of Feb calls. Let me know depending on your availability.

**Comment by sebastienlevert** [comment]
Let's do the 13th of Feb, it will be easier for me!

Thanks!

**Comment by VesaJuvonen** [comment]
Thanks for confirming. I've added you on the schedule/agenda for 13th of Feb.

**Comment by sebastienlevert** [comment]
Thanks!

--
Sébastien Levert / Office Development MVP & Architect
slevert@outlook.com / 514-833-8704
http://www.sebastienlevert.com
________________________________

**Pull request merged**
