### PR TITLE
adding react-skype-status sample to demonstrate the usage of UCWA SDK

### PR DESCRIPTION
**Pull request by baywet**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | 

Adding a new sample leveraging the UCWA JS SDK talking to skype API's in order to get information from users (name, status...)
That solution leverages react as well as the persona card from Office Ui Fabric and subscribes to status changes

### CODE REVIEW

**Comment by baywet** [comment]
cla signed, contribution guide enforced. Everything should be good.
Sorry if there are a lot of commits, I checked the detailed guidelines after starting the PR.
Let me know if you want me to squash commits

**Comment by VesaJuvonen** [comment]
Cool stuff, absolutely appreciated. Thx Vincent.

**Comment by baywet** [comment]
you're welcome! (for both PR's) let me know if you want me to jump on a call next time you talk about the samples

**Comment by VesaJuvonen** [comment]
@baywet - just to follow up on this. We do absolutely welcome community demos on the contributions, so if you are interested on showing these in upcoming SPFx community calls, we can absolutely get you 10-15 min spot to show the capability and needed setups - for example, to concentrate on how you can then further extend things etc. Your call.

**Pull request merged**
