### PR TITLE
Made styles unique on security grid

### PR DESCRIPTION
**Pull request by hugoabernier**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                               |
| New feature?    | no |
| New sample?     | no                               |

## What's in this Pull Request?

A minor fix on @russgove's awesome security grid web part that fixes issues with other list web parts on the same page being affected.

Also made the web part more theme friendly..

### CODE REVIEW

**Comment by russgove** [comment]
Thanks Hugo!  I suck at css! Do your changes make the webpart pick up the theme color from the site?

**Comment by hugoabernier** [comment]
Yeah, I didn't test it extensively, so I'm sure that it could be improved, but it picks up the theme colors.

It was my pleasure. I'm always happy to help!

**Comment by russgove** [comment]
Hey I updated the readme file and added some animated gifs for the new
features but they dont seem to have been pulled. Are they in the queue or
should i do another PR?

**Comment by hugoabernier** [comment]
Do you mind submitting another PR? I don't seem to see the references to the animated GIFs or the updated readme. I'll process it as soon as I receive it, scout's honor!

**Comment by russgove** [comment]
Hey , the ARE there. I see them on the dev branch. I was looking on the
Master branch.

This as presented on the weekly calls about 3 years ago!

**Comment by hugoabernier** [comment]
Thanks, I'll look for them and will integrate the changes. We're trying to move away from the `dev` branch and accepting PRs directly to the `master` branch to help process PRs faster.

**Comment by hugoabernier** [comment]
@russgove I merged your PR and added the theme support we discussed. I hope you don't mind, it is such a cool demo I thought it deserved to look good in every environment :-)

**Comment by russgove** [comment]
Thanks Hugo. I'm looking forward to installing your updates in my
environment!

**Comment by hugoabernier** [comment]
I hope they live up to your quality standards!

**Pull request merged**
