### PR TITLE
Added the Aggregated Calendar Webpart using React framework

### PR DESCRIPTION
**Pull request by dhavalshah01**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                                |
| New sample?     | yes                               |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?

A new sample webpart created to display aggregated events from multiple calendar list in SharePoint using SharePoint Framework and React

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Great work on this. Really cool scenario to demonstrate. Would you be available for doing a live 10-15 min demo of this in any of our community calls?

**Comment by dhavalshah01** [comment]
Thanks Vesa ! Yes I would be available for love demo. When is it scheduled ?

Thanks,
Dhaval Shah
(M) 832-312-9454

**Comment by jleckard007** [comment]
dhavalshah01
I am trying to deploy this frame work and the issue I am having is I don't know what to deploy to the CDN I don't get/ see a deploy folder.  I did see a deployAzureStorage folder but when I added that it did not work for the CDN .  I updated the Manafest to point to my CDN.  Can you please help??

**Comment by dhavalshah01** [comment]
Did you execute the below commands  in the following order ?

gulp clean
gulp build
gulp bundle 
gulp package-solution

this should create a CDN files in temp/deploy folder and sppkg file in the sharepoint/solution folder.

If you are still facing issue, I would suggest going through the below articles.


Article | Link
-- | --
Getting Started with SharePoint Framework (SPFx) | http://www.qipoint.com/blog/getting-started-with-sharepoint-framework-spfx/
Setting up Developer Environment for SharePoint Framework (SPFx) | http://www.qipoint.com/blog/setting-up-developer-environment-for-sharepoint-framework-spfx/
SharePoint Framework (SPFx) (Part 1) Create a simple Client Side Web Part | http://www.qipoint.com/blog/create-your-first-client-side-web-part-using-sharepoint-framework-spfx-part-1/
SharePoint Framework (SPFx) (Part 2) Create a Simple Client-side Web Part | http://www.qipoint.com/blog/create-your-first-client-side-web-part-using-sharepoint-framework-spfx-part-2/
SharePoint Framework (SPFx) (Part 3) Deploying and Shipping Your Client-side Web Part with Office 365 CDN | http://www.qipoint.com/blog/sharepoint-framework-spfx-part-3-deploying-and-shipping-your-client-side-web-part-with-office-365-cdn/

**Comment by jleckard007** [comment]
I re-downloaded the repository.  I also re-installed and ran gulp server
also all the commands you suggested above.  I have no issues with other
packages I have attempted to deploy.  Below is a screen shot of what I get
in  the temp folder I did get the package in sharepoint folder. please help
I really need this solution.
Respectfully
Jennifer

**Comment by jleckard007** [comment]
I am not sure if this helps but I also get the below.

**Comment by dhavalshah01** [comment]
@jleckard007  Can you share the screenshot of the error ? I don't see the screenshot in previous message.

**Comment by jleckard007** [comment]
I got this working
Thank you for your help

**Pull request merged**
