### PR TITLE
adding vue-js-org-chart sample

### PR DESCRIPTION
**Pull request by serdarketenci**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?      |  no
| New feature?   | no
| New sample?  |   yes                               |
| Related issues? | none |

## What's in this Pull Request?
A simple Organisation Chart webpart using Office UI Fabric, VueJS, REST API.

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Hi @serdarketenci!

I just checked out your sample and it looks very nice! I'm going to merge your PR but before that I was hoping you could do a couple of small fixes:

1. If I add the web part to a site home page, it loads when I open the site with a URL that ends with a slash:

https://mydev.sharepoint.com/sites/sitename/

but it doesn't open, when the URL doesn't end with a slash, e.g.:

https://mydev.sharepoint.com/sites/sitename

The same problem also occurs, if I browse the page via the SiteAssets library, e.g.

https://mydev.sharepoint.com/sites/sitename/SiteAssets/Home.aspx

The problem occurs because the site root URL for the API call to get the Employees list is formed by leaving out the bit after the last slash, so in the problem cases the URL ends up being

https://mydev.sharepoint.com/sites/_api/web/lists/getByTitle('Employees')/items?$top=2000&$select=Id,Title,EMail,JobTitle,WorkPhone,PhotoUrl,ManagerID/Id&$expand=ManagerID

or 

https://mydev.sharepoint.com/sites/sitename/SiteAssets/_api/web/lists/getByTitle('Employees')/items?$top=2000&$select=Id,Title,EMail,JobTitle,WorkPhone,PhotoUrl,ManagerID/Id&$expand=ManagerID

instead of this correct one:

https://mydev.sharepoint.com/sites/sitename/_api/web/lists/getByTitle('Employees')/items?$top=2000&$select=Id,Title,EMail,JobTitle,WorkPhone,PhotoUrl,ManagerID/Id&$expand=ManagerID

Could you fix the logic so that the web part always gets the site root URL reliably for the API call regardless of the URL format?

2. Could you change the "skipFeatureDeployment" in package-solution.json to false? The installation instructions you've provided in the README are spot on, but someone might still accidentally end up deploying the web part tenant wide even though it is required to be deployed for each site individually because of the Employees list.


Thank you for these fixes and for your great sample in general! Looking forward to merging it! :)

Laura

**Comment by KEMiCZA** [comment]
@serdarketenci I think you need to initialize the SPFx context first when using the PnPjs library:
https://pnp.github.io/pnpjs/documentation/getting-started/#using-pnpcommon-setup
In file OrgChartWebPart.ts add the following code:
```typescript
import { setup as pnpSetup } from "@pnp/common";

public onInit(): Promise<void> {

  return super.onInit().then(_ => {
    pnpSetup({spfxContext: this.context});
  });
}


```

**Comment by serdarketenci** [comment]
Hi @LauraKokkarinen, @KEMiCZA 

Thanks for fixing the OrgChartWebPart.ts and package-solution.json files :)

**Comment by LauraKokkarinen** [comment]
Thanks @serdarketenci, works great now! Keep up the good work. :)

Laura

**Pull request merged**
