### PR TITLE
Adding react-teams-tab-field-visit-mashup sample

### PR DESCRIPTION
**Pull request by BobGerman**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes?                               |
| Related issues? | none |

## What's in this Pull Request?

Adding the "Field Visit Demo" SPFx tab for Microsoft Teams. Initially developed to spur ideas at the SharePoint Developer Kitchen (Bellevue, summer 2018), this demo shows a mashup of content in SharePoint, Graph API, and external web services all relating to a customer visit. The sample demonstrates:

- A Teams tab using SharePoint Framework
- Accessing the hosting Team using the teams context and the Graph API
- Deep linking to a SharePoint Framework tab
- A mashup using React components

## Guidance

Requires content to be set up correctly in a Team's associated calendar and SharePoint site. Detailed instructions are included.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @BobGerman, appreciated. Readme is missing the view tracking image, which will be adding there as a quick fix, otherwise really cool setup. Would you be interested on doing a live demo of this one in any of the upcoming SharePoint Framework community calls?

**Comment by BobGerman** [comment]
Thanks for fixing the readme.

It would be brilliant to present this on an SPFx community call! I’m working on a series of blog articles that explain it and some of the techniques used, especially how to do deep linking into an SPFx tab which AFAIK isn’t yet documented in one place. It would probably be good to wait for the blogs, which might not get finished till after SPC. Could the community call wait till then?

See you at SPC!

**Comment by VesaJuvonen** [comment]
Thanks Bob, from the timing perspective, we could agree something like 6th of June SPFx community call, if that works for you... just trying to lock down the date to get a demo spot on calendars. Would that work for you?

**Comment by VesaJuvonen** [comment]
Thx @BobGerman - I've added you to the agenda for 6th of June based on this. Looking forward on catching up at the SPC.

**Pull request merged**
