### PR TITLE
Bootstrap Slider

### PR DESCRIPTION
**Pull request by davidhartman**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | n/a

#### What's in this Pull Request?

This example demonstrates how to not only use the SharePoint Framework deploy feature, which creates a list, content type, and site columns when deployed. It also demonstrates how to  create a bootstrap slider using the SharePoint Framework and uses external references to bootstrap and jquery.

Thanks for your contribution! Sharing is caring.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx David, appreciated. Would you be available for doing a demo on this in the May monthly community call on next Tuesday (9th of May)? This would be 10-15 min spot for a quick demo and walk through. Call is at 8 AM PT and you can get invite from http://aka.ms/sppnp-call.

**Comment by davidhartman** [comment]
Vesa -
Unfortunately I'm going to be traveling all day on May 9th, so I won't  be able to give the demo then. However, I should be able too next month. If that's OK? I truly appreciate the opportunity to share this!

**Comment by VesaJuvonen** [comment]
No worries David, Let's follow up on this closer to June month call. Or alternatively you could demo this also in SPFx SIG. That would be next Thursday at 7 AM PT.

**Comment by davidhartman** [comment]
Vesa -

Unfortunately I can't make the SPFx call either due to a previous commitment. I'm truly sorry!

**Comment by VesaJuvonen** [comment]
No worries - there's always a next time as well. Thanks for confirming your availability fast and sorry for delayed response.

**Pull request merged**
