### PR TITLE
added react-display-hierarchy

### PR DESCRIPTION
**Pull request by nanddeepn**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?
Added sample react-display-hierarchy.
At the time of developing this sample, the Office 365 UI fabric does not have any control for displaying hierarchical information. This web part helps to display the hierarchical information from SharePoint list.

## Guidance
At the time of developing this sample, the Office 365 UI fabric does not have any control for displaying hierarchical information. This web part helps to display the hierarchical information from SharePoint list.

### CODE REVIEW

**Comment by nanddeepn** [comment]
Hello,
During the pull request, below files were appearing in the delete and I was unable to exclude them.
1. samples/react-content-query-webpart/Misc/editor.gif
2. samples/angular-ngofficeuifabric-file-upload/src/webparts/angularFileUpload/app/services/baseSvc.ts

Please discard deletion of above 2 files. Apologies for the inconvenience caused.
Thank you

**Comment by VesaJuvonen** [comment]
@spplante - any change you had time to check this out as you are the original creator of the particular web part. We do encourage people rather extend than create new ones, so would love to be able to merge this, but also don't want to cause you surprises.

**Comment by VesaJuvonen** [comment]
hi @nanddeepn - the challenge is that I cannot avoid deleting those files if we merge this PR... which would mean that we would have to manually fix them. any chance you could set up a new PR which will not delete them?

**Comment by spplante** [comment]
@VesaJuvonen Not sure I totally understand what's going on here haha, what does this have to do with my content query WebPart? I see that there is one GIF image from my WebPart in the PR (Not sure why), but otherwise not sure how I can help :/

**Comment by nanddeepn** [comment]
> hi @nanddeepn - the challenge is that I cannot avoid deleting those files if we merge this PR... which would mean that we would have to manually fix them. any chance you could set up a new PR which will not delete them?

**Comment by nanddeepn** [comment]
Hi @VesaJuvonen ,
I will set up a new PR soon. Thank you

**Comment by nanddeepn** [comment]
Hi @VesaJuvonen ,
New PR is setup at [https://github.com/SharePoint/sp-dev-fx-webparts/pull/673](url)
Please do the needful. Thank you in advance.

**Comment by VesaJuvonen** [comment]
Closing as this was merged with the #673.

**Pull request closed without merging**
