### PR TITLE
Added a Site Url parameter on top of the Web Url parameter

### PR DESCRIPTION
**Pull request by spplante**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | #288 and #292

#### What's in this Pull Request?

Instead of having all the site collections and subsites urls mixed in the **Web Url** property of the React Content Query WebPart, I added another cascading property **Site Url** on top of it, which allows to narrow down drastically the amount of results found in each of the dropdown. The way it works now is much more user friendly, letting the user choose his site collection first, then select the subsite in a dedicated dropdown that shows exclusively subsites from the previously selected site collection.

Before :
Before

After :
After 

Also, since the dropdown was driven by a search query, the webpart was able to fetch a maximum of 500 sites/subsites mixed together, which was definitely a bottleneck for big businesses with lots of sites. 

Now, for both **Site Url** and **Web Url** dropdown, I modified the way the search request works, by adding a recursive promise logic that executes the needed amount of requests (each fetching 500 urls) until all results are fetched.

This means both properties can now fetch **unlimited** urls in their dropdown using the recursive approach, which should avoid any kind of missing site behavior even with thousands of sites.

### CODE REVIEW

**Comment by spplante** [comment]
@VesaJuvonen, not sure why these files are conflicting as I simply updated them, but one thing sure is the ones I am pushing are the correct files and they can override their previous versions.

**Comment by VesaJuvonen** [comment]
Thx Simon, all good with this one after some manual merge conflict resolution. Good changes, but you also most likely want to double check the design for the site collection URL resolution. I'd assume that 80-90% of times you'd be pointing this web part to particular site collection... but currently selection logic makes that really hard if you have hundreds, thousands of hundred thousand site collections... which would not be that rare.

I'd suggest that you by default select current site collection as the URL for site collection selection and then simply have the option to select something else... Current UI works great in dev tenants, but not in mid-sized or larger company deployments. Pic shows the problem and scanning through tens of thousands of URLs in the drop down does not really work that well. 

image

**Comment by spplante** [comment]
Hi Vesa,

I was having pretty much the same conversation with Sebastien Levert in regards to the current site collection and web being selected by default. This is definitely the next small update I will be working on! 

However, just to make sure there is no actual " blocking issue" for large-sized farms, if I understand correctly, the UI problem you are referring to is more "annoying" than "blocking" am I right? Or you can't actually select your site collection because the dropdown has a glitch when filled with too many items?

I am just asking to gauge how fast I should start working on this haha, but in both cases this is the next update anyway. Thanks!

**Comment by VesaJuvonen** [comment]
There's no blocking issue current - that's correct, so no worries on getting next version out. Technically web part is though basically unusable when there are thousands of site collections since it's impossible to find the current or an other site collection from the list... browsers don't simply render that nicely. 

I can select a site collection - but most likely not the one which I'm looking to select.

**Comment by spplante** [comment]
I just don't get why you say it's impossible to find the actual site you are interested in? Because the browser "lags" too much since there is thousands of items in the dropdown? Or because it's not in the actual list?

Because if the dropdown really is unusable when filled with thousands of items, to me it's a bigger issue that will only be partially fixed even If the current site is preselected : It will fix 80% of the cases where most users just want to fetch data from the current site, but it will not fix the cases where a user wants to select another site collection, the dropdown will still be unusable.

If it's only a matter of the dropdown displaying too many items, making it "difficult" to find the site your are looking for, it's a different story :)

In all cases I will try to mock thousands of sites just to see how the UI reacts.

**Comment by VesaJuvonen** [comment]
Challenge is really that browser lag and challenge of finding the right site collection. Scrolling down the list of site collections in alphabetical order takes ages in the case of tens of thousands of site collections due to browser lag. You can easily mock this by creating thousands of items in alphabetical order and then trying to find site collection with 'url' of "mou" - moving to even to right area on the list is hard.

**Comment by spplante** [comment]
Ahhhhh ok I totally get it now. I will try to come up with the site collection preselection in the following weeks :)

**Comment by spplante** [comment]
One detail @VesaJuvonen, what is the usual schedule where you guys merge SharePoint:dev to SharePoint:master for the sp-dev-fx-webparts repository? Is it at the end of each month? I am just asking so I can time myself accordingly next time I push stuff to the dev branch :)

Thanks!

**Comment by VesaJuvonen** [comment]
Timing with the spfx repositories is more flexible - we do merge things over quite fast from the dev side - typically within 1-2 business days... or even in a matter of hours. Really depends on the overall situation and what's pending on the dev side.

**Comment by spplante** [comment]
Gotcha!

**Pull request merged**
