### PR TITLE
Angular search

### PR DESCRIPTION
**Pull request by davidhartman**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| New sample? | yes |
| Related issues? | none |
#### What's in this Pull Request?

This is an angular search client side webpart that uses the new SharePoint Framework. This sample uses Angular v1.x. The webpart hits SharePoint's Search REST API based on the content type the author selects in the property pane. The results returned are displayed using the List components from ngOfficeUIFabric. 

Thanks for your contribution! Sharing is caring.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx David, we'll have a look on this during upcoming days.

**Comment by davidhartman** [comment]
Thanks Vesa! Please let me know if you have any questions!

**Comment by VesaJuvonen** [comment]
Sorry for the delay David, we'll start processing these more detailed next week (24th of Oct forward)

**Comment by davidhartman** [comment]
Not a problem Vesa! Thanks for keeping me informed!

**Comment by VesaJuvonen** [comment]
thx David. Slightly complicated setup with publishing requirements, but does provide value as an sample on the search usage with Angular. If you btw want to have your company logo in the monthly messaging around the people who have contributed, would ask to send me a link to a logo. See following as a reference from Oct - http://dev.office.com/blogs/PnP-October-2016-Release

**Comment by davidhartman** [comment]
Thanks Vesa! Sorry about the complicated setup with the publishing features but I thought it would help in pulling back relevant results from search, and I figured setting up a custom content-type would be overkill. Here is a link the my company's logo: [Slalom's Logo](https://www.slalom.com/sites/all/themes/slalom_bootstrap/images/slalom-logo-default@2x.png).

Let me know if you have any problems getting the logo.

**Pull request merged**
