### PR TITLE
Added new sample webpart which add js, css file references to modern pages.

### PR DESCRIPTION
**Pull request by siddharth-vaghasia**
Added react-js-css-reference sample webpart

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | yes                               |

## What's in this Pull Request?

This repo is a react based SPFx web part and extension that allows users to add/modify/delete custom JS and CSS file references using SPFx application customizer extension all modern pages within SP online site. This web part provides an interface to JS and CSS file references so that we don't have to modify code when we need to change references or add new references in the future. As part of security measures, these actions on web part can be only accessed by users who have Manage web permission on site.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks @siddharth-vaghasia . 

Would you be interested in demoing this in an upcoming SPFx community call?

**Comment by siddharth-vaghasia** [comment]
@hugoabernier ....would love to......Please let me know when next slot is available...

**Comment by hugoabernier** [comment]
We have a slot open on the SPFx community call on June 18th, if that works for you?

**Comment by siddharth-vaghasia** [comment]
> We have a slot open on the SPFx community call on June 18th, if that works for you?

yes....,it works :)

**Comment by hugoabernier** [comment]
Perfect! I have you confirmed for June 18th

**Pull request merged**
