### PR TITLE
Adds SPFx React Jest Testing sample

### PR DESCRIPTION
**Pull request by VelinGeorgiev**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                            |
| New feature?    | no                        |
| New sample?     | yes                       |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?

Adds SPFx React Jest Testing sample. 

This sample uses the popular Jest Testing Framework with a SPFx client side solution. 
It is a SPFx-Jest-Enzyme-Sinon starter kit so you can start writing and debugging unit tests in typescript for your SPFx solution.

The setup includes unit tests examples, code coverage reports in different formats, visual studio code unit test debug configurations for typescript, setting a coverage threshold (gates) for continuous integration and continuous deployment scenarios.

I added detailed README file, please refer to it and let me know if any questions.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx Velin, appreciated. Absolutely a topic which we should cover in our community calls so that we can show a model for doing this We would have for example available spots for the 24th of May SPFx call, if you have availability and interest to cover this sample?

**Comment by VelinGeorgiev** [comment]
Thanks @VesaJuvonen! We definitely should demo that!

I will not be available from 23th until 29th of May. Feel free add spot for me in community call anytime after these dates.

**Comment by VesaJuvonen** [comment]
Hi @VelinGeorgiev - would you be fine for having this covered on 7th of June SPFx SIG? - Just to get this to the calendar.

**Comment by VelinGeorgiev** [comment]
Hey @VesaJuvonen I will join the call and demo it. Feel free to add me to the agenda.

**Comment by VelinGeorgiev** [comment]
Hey Vesa, @VesaJuvonen, Would it be a good idea if I turn that into a document/getting started guide part of the SharePoint Frameworks official documents. I know that this is not the officially supported framework, but the documentation does not have any testing guidance at the moment, in the same time I would like to promote more testing because I think this is the way to go when building enterprise ready solutions.

**Pull request merged**
