### PR TITLE
React-Carousel  and New Version of Happy Birthday Web Part

### PR DESCRIPTION
**Pull request by joaojmendes**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     |  yes                            |
 

## What's in this Pull Request?

> New Sample React-Carousel, Show Images and Videos in Carousel
>

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Awesome stuff @joaojmendes, please do let us know, if you are interested on doing a live demo of the carousel web part in one of the upcoming community calls.

**Comment by cj31016** [comment]
Excellent stuff. I'm doing some testing with it, but all birthdays it pulls in are from the beginning of the year. Anyway to force it to pull current bdays? Thanks for the effort here.

**Comment by joaojmendes** [comment]
Hello Vesa,

My apologies for only answering now.
I'm going on vacation next week and only return to work in the first week of September, I am very pleased to make the presentation of the Carousel Web Part in September.

Thank you very much for the opportunity to participate and be able to contribute to the community.

I have some problems in speaking English but I'm sure they'll understand me... 🙂

Thank you very much.
João

________________________________

**Comment by VesaJuvonen** [comment]
No worries on the delay around this. Let's sync on this closer on the September, but have now added you a spot for the 12th of September. We can agree on the right web part closer as your React-Directory is also a great one. English will get better by talking it and key is the information, not that it's perfectly pronounced using Oxford-English... I'm good example of this as well, so no worries there. Your contributions are really powerful and community is happy to hear about them.

**Comment by VesaJuvonen** [comment]
Just a reminder on the spot in the tomorrow's call. I won't be there personally as taking long weekend off, but we have other people driving the call in typical ways.

**Comment by joaojmendes** [comment]
Thank you very much for the opportunity to participate on this awesome community session.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
