### PR TITLE
Added page contributors webpart

### PR DESCRIPTION
**Pull request by SPParseError**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | no

#### What's in this Pull Request?
Added a new webpart sample : displays page contributors in reverse chronological order.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Stéphane, great sample. Would you be available for a quick demo around this in our community calls - for example on the 17th of August Special Interest Group call for SPFx / JavaScript dev?

**Comment by SPParseError** [comment]
Hi, I would love to. 
I am on holidays on the 17th August and may not have a sufficient connection, can I do it in the next one?

**Comment by VesaJuvonen** [comment]
That works as well - Next one would be on 31st of August, if that works for you? - I'll make sure that we track this internally for the call after your confirmation.

**Comment by SPParseError** [comment]
Ok for me, thanks !

**Comment by VesaJuvonen** [comment]
thx Stéphane, I'll inform Patrick Rodgers on this and we'll get you for the demo section in that call. Thx for volunteering. So - based on this - let's do the 31st of August for your demo.

**Comment by SPParseError** [comment]
@VesaJuvonen Hi, i don't have any news for tomorrow. What is the process ? 

Best Regards, 
Stéphane

**Comment by VesaJuvonen** [comment]
There's no actual news really - just the typical process and was planning to confirm your availability anyway today. So - if you're fine for the demo, we'll get you 10-15 min spot for tomorrow's SPFx SIG (recurrent bi-weekly invite from https://aka.ms/sppnp-js-sig-call). We'll update you as a presenter in the call and when it's your turn, we'll just switch to your screen sharing and audio.

Community call is at 7 AM PT tomorrow Thursday 31st of Aug. I'll send agenda details beforehand few hours before the meeting using social media channels. Works for you?

**Comment by SPParseError** [comment]
Ok, world for me.

**Pull request merged**
