### PR TITLE
Add react-file-upload sample

### PR DESCRIPTION
**Pull request by raminahmadi1986**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes

#### What's in this Pull Request?

Add react-file-upload sample.
The file upload sample allows users to upload multiple files to a document library or as file attachments.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Ramin, appreciated. Seems that this one got some other commits inside of it as well, but that seems to be fine for now, so these are not mixing anything in the main branches, so all good. Nice and cool setup. Would you be interested in doing a live demo of this one in one of our community calls? - Would mean 10-15 min spot to demonstrate the functionality and code for other attendees in Skype call. Calls are also recorded and then shared in the SharePoint Dev YouTube channel at http://aka.ms/spdev-videos. If you are up for it, we can schedule a spot for you.

**Comment by raminahmadi1986** [comment]
Thanks Vesa, yeah I would love to, I'm just a bit worried about my English.

**Comment by VesaJuvonen** [comment]
Hi Ramin, really up to you. Tech is the key point, not the "perfect English". We could potentially have even a spot on this week's Thursday call - which would be on 1st of March at 3 PM GMT... if you want to take it. It would be then a functionality demo and explanation of the code on what happens. FYI @patrick-rodgers

**Comment by patrick-rodgers** [comment]
This would be great to have on the call - and certainly no worries on language.

**Comment by raminahmadi1986** [comment]
Ok so let's do it.

**Comment by patrick-rodgers** [comment]
Awesome, you are on the agenda! Thanks!

**Comment by VesaJuvonen** [comment]
and just to be 100% clear on the process - Please join on the bi-weekly SPFx call - you can get the invite from https://aka.ms/sppnp-js-sig-call. We'll then upgrade you as a speaker for the call. We have 3 different community demos tomorrow and you'll be the last one to go around 15-10 to the next hour... around 3:45 PM GMT. The call will be recorded and shared from official SP Dev video channel at http://aka.ms/spdev-videos within 24 hours after the call. If you have any challenges on joining or getting access to call details, please let us know. Thx for volunteering on this one, really appreciated.

**Comment by raminahmadi1986** [comment]
I've accepted the call and ready for tomorrow :)
I've also prepared a demo so I can share my screen and demonstrate this web part on the call.

**Pull request merged**
