### PR TITLE
[react-search-refiners] Added SearchBox WP + "Result Source Id" and "Enable Query Rules" parameters

### PR DESCRIPTION
**Pull request by FranckyC**
| Q               | A
| --------------- | ---
| New feature?    | yes

#### What's in this Pull Request?
Added a search box to the react-search-refiners Web Part (as a standalone and optional Web part).
Added the support of result source (as id) and query rules parameters.

### CODE REVIEW

**Comment by FranckyC** [comment]
Hi @VesaJuvonen, any updates on this one? Also, I could demo this on a in PnP call if you're looking for content.

**Comment by VesaJuvonen** [comment]
thx Franck, appreciated. Sorry for the small delay on this one. Great improvements and great to see evolving also existing samples.

**Comment by VesaJuvonen** [comment]
On the demo - We would have SPFx SIG this Thursday and we should have at least one free spot for community demo, if you are interested. Would be great to get the improved capabilities also recorded in one of the community calls. 

FYI @patrick-rodgers

**Comment by FranckyC** [comment]
@VesaJuvonen Unfortunately, I won't be available this Thursday neither the next week due to the MVP Summit. Maybe the next call if you have free slots.

**Pull request merged**
