### PR TITLE
Add react-site-provisioning-manager sample

### PR DESCRIPTION
**Pull request by AhmadiRamin**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                               |
| New sample?     | yes                               |

## What's in this Pull Request?

This sample helps administrators to manage site provisioning templates using SPFx web part and Azure Functions.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi @AhmadiRamin - we'll get this merged in a pity - but curious on your availability on doing a live demo of this in one of the upcoming community calls. This has really good pieces and it could be actually demoed in both calls - SPFx and the provisioning/solution design calls... which I'd actually even prefer, if you agree on that...

So the offered times would be following:
- Dev Generic - 5th of September
- SPFx - 12th of September
- Dev Generic - 19th of September
- SPFx - 26th of September

Each call has currently one spot available, so you can the one which works for you.

**Comment by AhmadiRamin** [comment]
Hi @VesaJuvonen, as I'm on holiday up to 10th of September, any of those calls except the first one works for me and I'm happy to do the demo on either SPFx or Dev Generic, I'll leave it to you :)

**Comment by VesaJuvonen** [comment]
Happy to get you a spot on the 19th of September then as this is really also on the provisioning side of the house and demonstrate a nice overall solution pattern - Does that work? Agreed?

Also just double checking the status for this week though... you are still doing following demo on 29th of August? or do we need to reschedule that one - see for additional context https://github.com/SharePoint/sp-dev-fx-extensions/pull/235.

**Comment by AhmadiRamin** [comment]
Thanks Vesa, 19th of September works fine, and I'm ready for the demo on 29th of August, I've already planned to have free time for that, so don't worry about it.

**Comment by VesaJuvonen** [comment]
Awesome - thanks @AhmadiRamin, really appreciated.

**Comment by LauraKokkarinen** [comment]
Hi @AhmadiRamin !

Thank you for sharing this brilliant sample with us! And sorry that merging this took a bit longer than expected; I had a little bit of trouble setting this up for testing. I made some additions to the installation instructions based on my experiences, so hopefully it will be smooth sailing for everyone else who want to try out your absolutely awesome web part! :)

Just in case you are wondering why I changed the order of the steps: 

For some reason creating the app registration at the same time when adding the Azure AD auth for the functions resulted in an error about user_impersonation scope not being found when trying to approve the permissions for the SPFx web part in the SharePoint admin center. This was resolved by creating an app registration in Azure AD first, setting the scope there manually, and only after that linking the app with the function auth. Nothing related to your implementation, just the platform behaving a bit funny.

Also, Visual Studio refused to pick up my cert from the Certs folder before I manually adjusted the csproj file. Which made me have an idea:

If you want to further develop this, rather than adding the certificate pfx file to a local directory folder, it could be added to the certificates of the Azure function (under Platform features -> SSL) and make your code fetch it from that cert store with a thumbprint. This way you don't need to provide the certificate password in the app settings for using the cert. Some example code here: https://laurakokkarinen.com/authenticating-to-office-365-apis-with-a-certificate-step-by-step/#c-sharp-code-for-your-solution

Can't wait for your community call demo. :)

Laura

**Comment by AhmadiRamin** [comment]
Thank you @LauraKokkarinen, I just started posting a blog and was about to change the readme based on that which you did it perfectly. it's such a pleasure to have you in the community :)

**Comment by LauraKokkarinen** [comment]
Oh, I forgot to update one thing in the instructions: In the CORS screenshot, there's URL https://ramadi.onmicrosoft.com when it should be https://ramadi.sharepoint.com. If you are planning on making other changes, that could be fixed at the same time.

Laura

**Comment by AhmadiRamin** [comment]
Good point, I also updated that screenshot.

**Pull request merged**
