### PR TITLE
Offline first react

### PR DESCRIPTION
**Pull request by AustinBreslinDev**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | no

#### What's in this Pull Request?
This webpart attempts to demonstrate how to do the offline first technique of retrieving requests from local storage first, then rendering the component on the page, then making the live request to a server, then redrawing if required (react looks after this in the Virtual DOM).

The webpart has a services folder, and that is the main part of this sample. The TSX file shows how to use this service.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @AustinBreslinDev, appreciated. Good technical demo of preferred patterns. Would you be interested in doing a life demo and code explanation of this one in one of our community calls? - We have bi-weekly SPFx community call where we typically have 2-3 demos from the community. We would book you 10-15 to explain the used code etc. In this case, the actual technical solution is pretty straightforward, but no harm doing a quick demo (even for 5 min) to increase awareness of the good techniques.

FYI @patrick-rodgers

**Comment by AustinBreslinDev** [comment]
Hi @VesaJuvonen ,

You can schedule me in for a demo, it shouldn't take too long it's a relatively simple front-end design practice. Please get back to me about when, as the meetings are during my working day.

I already have the SPFX bi-weekly community call in my calendar, the one from Patrick-Rodgers.

**Comment by patrick-rodgers** [comment]
Hi @AustinBreslinDev - this is great, if you are available we can get you in on this Thursday March 1st.

**Comment by patrick-rodgers** [comment]
Great, you are on the agenda! Thanks!

**Comment by VesaJuvonen** [comment]
and just to be 100% clear on the process - Please join on the bi-weekly SPFx call - you can get the invite from https://aka.ms/sppnp-js-sig-call. We'll then upgrade you as a speaker for the call. We have 3 different community demos tomorrow and you'll be the first one to go around 20 past on the hour. Call will be recorded and shared from official SP Dev video channel at http://aka.ms/spdev-videos within 24 hours after the call. If you have any challenges on joining or getting access to call details, please let us know. Thx for volunteering on this one, really appreciated.

**Pull request merged**
