### PR TITLE
New sample - PnP ListView with PnP Field Controls

### PR DESCRIPTION
**Pull request by AJIXuMuK**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                      |
| New feature?    | no                               |
| New sample?     |      yes                               |
| Related issues? | no |

## What's in this Pull Request?

The PR contains sample how to use PnP `ListView` control with PnP Field Controls to render columns.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Awesome stuff - thx @AJIXuMuK - let me know again your interest and availability for doing a community call around this. Next free spots would be on 9th of April.

**Comment by AJIXuMuK** [comment]
Hi @VesaJuvonen!

I'm available on April 9. Will be happy to make a demo!

**Comment by VesaJuvonen** [comment]
Excellent - looking forward. 9th of April it is then.

**Comment by hugoabernier** [comment]
@AJIXuMuK I was really looking forward to your demo... are you available to demo on April 23rd instead?

Thanks for your patience and understanding with this!

**Comment by AJIXuMuK** [comment]
Hey @hugoabernier!
Yes, I can do April 23d, or record the demo if it's easier. :)

**Comment by hugoabernier** [comment]
Perfect! I'll add you to the agenda on April 23rd.

I think people like to see live demos so they can ask questions... but I always have a backup of my demo recorded _just in case_ :-)

Thanks for being flexible!

**Pull request merged**
