### PR TITLE
Add react-VideoLibrary

### PR DESCRIPTION
**Pull request by russgove**
| Q               | A
| --------------- | ---
| Bug fix?        | no - yes?
| New feature?    | no - yes?
| New sample?      | no - yes?
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Please describe the changes in this PR. Sample description or details around bugs which are being fixed.

#### Guidance
*You can delete this section when you are submitting the pull request.* 
* *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
* *Please target your PR to 'dev' branch.*

Thanks for your contribution! Sharing is caring.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Russell, will get this one processed in upcoming days.

**Comment by VesaJuvonen** [comment]
Any interest on demoing this live in the SPFx bi-weekly SIG calls?

**Comment by russgove** [comment]
I could do that

**Comment by VesaJuvonen** [comment]
Hi Russ, I'm getting this processed now, but just wanted to follow up on the SIG call tomorrow Thursday - so wanted to double check your availability for doing a demo on this in that call?

**Comment by russgove** [comment]
Hi Vesa,
I can do that.  I just need to make sure its still working in my
environment.
Russ

**Comment by russgove** [comment]
OK, I got it upgraded to RC0.
I'll need to test it in the morning but I should be good to go.

**Comment by VesaJuvonen** [comment]
Excellent - sorry missed your latest comment. I do have some feedback on this existing PR, since there was some issues around additional files, whcih should not be included in the PR - like webpack-streaming on the root of the GitHub repo. Would appreciate if you'd do new PR with the RC version, so that we can get things in more cleaner way - if you don't mind. We could simply close this one and you can re-submit the updated one, if that works for you. Will process the new PR then faster to get things moving. Sounds good?

**Comment by russgove** [comment]
OK, I can do that

**Comment by VesaJuvonen** [comment]
Thanks one more time on the demo. No massive rush on the new PR, but obviously would be great to get the new sample referenced in the video which goes out tomorrow - I'll process the PR as it arrives. Absolutely depends on your availability.

**Comment by russgove** [comment]
PR was submited

**Pull request closed without merging**
