### PR TITLE
Added two samples (image magnifier and youtube webpart) furthermore react-peoplepicker is upgraded to drop 1.3.0

### PR DESCRIPTION
**Pull request by giuleon**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New samples?      | yes

#### What's in this Pull Request?

**1. react-image-magnifier:** -> New sample
This web part allows to magnify an image, displaying a resolution more detailed through a lens.

More details on my blog post:
http://www.delucagiuliano.com/sharepoint-framework-magnifying-an-image-through-a-lens/

**2. react-youtube:** -> New sample
This web part allows to search and view the Youtube videos, across the Youtube API, directly on a SharePoint page, furthermore the property panel offers the possibility to specify the api key, the number of items to display and it is also possible specify a Youtube Channel Id. 

More details on my blog post:
http://www.delucagiuliano.com/youtube-web-part-on-sharepoint-through-sharepoint-framework/

**3. react-peoplepicker** -> Upgraded to drop 1.3.0 
Upgraded to drop 1.3.0 and new properties that allow to specify the number of items to display and which entities retrieve (Users, SharePoint Groups, Distribution Lists, Security Groups).

More details on my blog post:
http://www.delucagiuliano.com/office-ui-fabric-people-picker-and-sharepoint-search-better-together-part-2-sharepoint-framework/

### CODE REVIEW

**Comment by giuleon** [comment]
Hi @VesaJuvonen, are there problem to merge this one ?

**Comment by VesaJuvonen** [comment]
Just time - lack of it... to double check things... will be merged soon to get it included in Oct release.

**Comment by giuleon** [comment]
Ok thanks 😉

**Comment by VesaJuvonen** [comment]
We would always request a sample in one PR to ensure that we can check stuff more efficiently, since now we'll need to cancel both of the samples, if either one is not working... so would rather request the second sample as new PR. thx.

**Comment by giuleon** [comment]
ok thanks

**Comment by VesaJuvonen** [comment]
thx Giuliano for this. Sorry for the small delay on getting things processed, our objective is to be much faster in the future.

**Comment by giuleon** [comment]
Thanks Vesa

**Pull request merged**
