### PR TITLE
Angular aad webapi

### PR DESCRIPTION
**Pull request by davidhartman**
| Q               | A
| --------------- | ---
| Bug fix?        | no 
| New feature?    | no 
| New sample?      | yes
| Related issues?  | n/a

#### What's in this Pull Request?

This is an Angular v1.x client-side webpart that communicates with a custom Web API that is secured by Azure AD.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx David, we'll get this processed soon.

**Comment by VesaJuvonen** [comment]
thx David, getting this merged. I'll do small adjustments to include proper image tracking on readme and also the version information which this one supports, but all good. We will soon release Release Candidate for SPFx, will use also this opportunity to check if you'd like to update your own web parts to that, or should we do that using PnP resources (me most likely)? - RC will cause some changes cross solutions, so happy to take the ball on this, if needed. From older drops to RC, changes are bigger than from RC to GA release.

**Comment by davidhartman** [comment]
thanks Vesa! I'm sure you're busy enough without having to make updates to my code, so I'll take care of it. Are you guys aiming for a specific date for all the code to be updated?

**Comment by VesaJuvonen** [comment]
Hi David, can't tell you the exact timing with RC at this point - but happening really soon. Thx for volunteering on doing the updates. RC is already pretty close to GA, so you should not be required to perform similar set of refactoring then on later stages.

**Comment by davidhartman** [comment]
Thanks Vesa. I just read the RC article and was wondering if would be OK if I just completely replaced the old webparts with the new code like the article recommends? I'd still save the ReadMe file though.

**Comment by VesaJuvonen** [comment]
That's most likely the easiest option. So - absolutely fine.

**Pull request merged**
