### PR TITLE
Fixed npm install for react-script-editor

### LINKED ISSUE #1027: Keep getting "Verification failed while extracting @microsoft/sp-polyfills@1.2.0"
## Category

- [x] Question
- [x] Bug
- [ ] Enhancement

When running "npm install" I am getting following error, already tried to very and clean the cache with no luck:
npm ERR! Verification failed while extracting @microsoft/sp-polyfills@1.2.0:
npm ERR! sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg= integrity checksum failed when using sha1: wanted sha1-iImCPTaoQl6Dxjxki9BWOfq/Wwg= but got sha512-SZARibyCQB+1j5b7g/6CrsUBA8pz9Yh1z+2RhXMlJcLyGkUmSriKgRmHnPjpjogQSGUAARTIFaYIMncfqL+8Pg== sha1-w6MYuEq9uEl8jKzi5LPU8hoPAII=. (1467748 bytes)

### PR DESCRIPTION
**Pull request by rsperre**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                             |
| New feature?    | no                               |
| New sample?     | no                               |
| Related issues? | fixes #1027, #1031  |

## What's in this Pull Request?
Regenerated package-lock.json due to it containing invalid references.

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Hi @rsperre ,

Thank you for creating this PR for fixing those issues!

This sample seems to have a dependency on event-stream-3.3.6 which had a security vulnerability and was removed from the npm registry. Because of this, the sample no longer builds and I can't verify your changes.

Would you mind fixing the issue? There are a few solutions presented here: https://stackoverflow.com/questions/53578201/npm-err-404-not-found-event-stream3-3-6

Thanks!

Laura

**Comment by LauraKokkarinen** [comment]
To clarify, I was talking about the knockout-sp-pnp-js sample in my previous message.

I just noticed that your PR also has files from other samples. Could you please separate changes to different samples to different PRs as mentioned in the contribution guidelines (https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/.github/CONTRIBUTING.md)? Thank you, and sorry for nagging. :)

Laura

**Comment by rsperre** [comment]
No problem, not quite sure how these commits (from Vesa and yourself) were included with mine.  I will close this request and open a new one :)

**Comment by rsperre** [comment]
@LauraKokkarinen - It seems like these extra commits originated from the master branch - The dev branch might need rebasing?

**Pull request closed without merging**
