### PR TITLE
Replaced the Angular ToDo sample

### PR DESCRIPTION
**Pull request by waldekmastykarz**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | no
| Related issues?  | n/a

#### What's in this Pull Request?

Replaced the Angular ToDo sample. The latest version of the sample doesn't use ngOfficeUIFabric which collides with Office UI Fabric used by the SharePoint Framework. Instead all CSS styles are embedded in the web part.

### CODE REVIEW

**Comment by Danny-Engelman** [comment]
I do not understand this code, can you please explain it,



As I read it it does **sequentially**:

1. Create Promise
2. Find todo by ID
  2A. delete item
  2A. resolve Promise
or
  2B. reject Promise
3. return Promise

If it is meant to be an Angular example, the above code is totally different from  the Angular documentation:

```
// perform some asynchronous operation, resolve or reject the promise when appropriate.
  return $q(function(resolve, reject) {

  });
}
```

What does SPFx do with Promises that we have to use this pattern?

**Comment by waldekmastykarz** [comment]
It's just a different way of working with Angular promises. In this particular example, using promises is not necessary, as the web part uses a static data set, but in case you would replace the static data with data from SharePoint you could easily replace the piece of code responsible for retrieving the data and reuse everything else.

**Comment by Danny-Engelman** [comment]
So with SPFx one does not need the Angular notation ?

```
  return $q(function(resolve, reject) {

  });
```

**Comment by waldekmastykarz** [comment]
You can use `$q` in two ways: either using the promise-like convention you mentioned or using deferred like I did. SPFx doesn't infer any limits in this case.
For more information see https://docs.angularjs.org/api/ng/service/$q which shows both conventions.

**Comment by Danny-Engelman** [comment]
Cool!

So this functions **returns** the Promise at the start of execution?

Never imagined Promises could work that way

But why is the ``return deferred.promise;`` at the **end** of the Function then?

**Comment by waldekmastykarz** [comment]
When working with $q the same way you work with promises, all of the code is wrapped in the promise. When working with deferred, that's not the case, so if you would return the promise from deferred immediately, none of the code would be executed. This is why returning the promise is the last line of code in the function.

**Comment by Danny-Engelman** [comment]
So the resolve or reject execute before the promise is returned?


Danny Engelman <http://www.engelman.nl/>
danny@engelman.nl
http://www.LinkedIN.com/in/dannyengelman

► 365Cooperatie.nl
► bikeswap.org - borrow a motorcycle, loan a motorcyle

*Learn from the past*
*Live in the present*
*Believe in the future*

2017-03-12 14:08 GMT+01:00 Waldek Mastykarz <notifications@github.com>:

**Comment by waldekmastykarz** [comment]
If you reject or resolve a deferred object before returning its promise, then the promise will be returned finished already and the code following the promise will execute immediately. If you return the promise before resolving/rejecting it, then the code following the promise will wait until the promise is resolved/rejected.

**Comment by Danny-Engelman** [comment]
I get it now!!... its kinda like Promises **inside** Promises

If the example confuses me.. I must be stupid

I would do it something like this pseudo code.

````
    public deleteTodo(todo: ITodo, matchingKey: String = 'id'): ng.IPromise<{}> {
        return $q((resolve, reject) => {
            const lengthBeforeDelete = this.items.length;
            this.items = this.items.filter((item:ITodo) => {
                return item[matchingKey] !== todo[matchingKey];
            });
            this.items.length < lengthBeforeDelete ? resolve() : reject();
        });
    }
```

**Comment by Danny-Engelman** [comment]
No, I still don't get your code... 
**you return the deferred (which is already resolved) at the end of your function**

I can't get it how this can work as Promise.. where the Promise is returned first and the resolve executes later.

The Angular page you refer to uses ``setTimeout``

**Comment by waldekmastykarz** [comment]
As I mentioned before: in this particular example using promises has no point since the returned data is already available and the promise is resolved before it's returned. If you would however want to retrieve the data from SharePoint or another API, then you would first return the promise and resolve it later, like: https://github.com/waldekmastykarz/demo-sharepoint-todo-angular/blob/db9bdcea16051f061e16cbe7b935a2b74c618e04/app/data.service.js#L15-L43

**Comment by Danny-Engelman** [comment]
Now we are there... "Then you would First return the Promise"

So the current code is, in your words, an example,
and uses the wrong pattern to do Promises.. since then the code needs to
return the Promise first..

Certainly one of the more intriguing examples I have seen in a long time...

**Comment by waldekmastykarz** [comment]
I'm afraid you drew a wrong conclusion. Imagine the following scenario: you have an Angular service that retrieves data from an API and caches it for subsequent requests. The first time the promise is returned and is being resolved with a delay after the data from the remote API has been retrieved. The second time around, when the data is already available in the cache, the returned promise would already be resolved without any delay.

**Comment by Danny-Engelman** [comment]
So how does that apply to your function:

The only line it returns a Promiseis 89

That means 73 - 87 always execute **prior** to the Promise being returned.

It **is a sync function**,  
the only way to turn this into a Promise is to wrap it in a ``return $q`` 

that means your ng Promise example code is missing a (rather vital) statement

image

**Comment by waldekmastykarz** [comment]
As you've noticed yourself: the last line does return a promise. Even if you would wrap the whole code block in `$q` the result would be the same: a promise.

Promises can be returned from sync functions. The case of a service caching data, that I mentioned previously, is a perfect example of working with promises both in sync and async flows. To methods using the service it doesn't matter if the flow inside the method they are calling is sync or async. In either case they receive a promise and continue once it's resolved. When the flow is async, the promise is resolved after a slight delay. In a sync flow the promise is resolved immediately.

**Pull request merged**
