### PR TITLE
Added sample react-graph-feedback-form

### PR DESCRIPTION
**Pull request by sergeyzheleznov**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                            |
| New feature?    | no                             |
| New sample?     | yes                              |
| Related issues? |  |

## What's in this Pull Request?

Sample SPFx React web part which allows sending emails using Microsoft Graph.

## Guidance

Sample SPFx React web part which allows sending emails using Microsoft Graph.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx @sergeyzheleznov for the sample. Relatively simple but definitely absolutely valuable for the community as showing the key scenarios with Microsoft Graph.

**Comment by LauraKokkarinen** [comment]
Hi @sergeyzheleznov ,

Would you like to do a short demo about this sample in one of our upcoming SPFx community calls?

Laura

**Comment by sergeyzheleznov** [comment]
Hi @LauraKokkarinen  ,

Yes, sure I could make a short video presentation and send it to you. If there is something special about the video format, content structure, or timing that I should know about, please let me know. 

It's great that I can help support the community!

Sergei

**Comment by LauraKokkarinen** [comment]
Hi @SergeiZheleznov ,

I was actually hoping that you could join our community call live and deliver your presentation right there and then! :) It gets recorded, so you get a video out of it automatically as well, here's an example: https://www.youtube.com/watch?v=m3tf1Bc6ilQ

How does that sound? The next SPFx community call that still has available spots for demos is on Thursday the 24th of October (of course, can be later too if that date doesn't work for you). Here's a link to the recurring calendar invite to the calls: https://aka.ms/spdev-spfx-call

Laura

**Pull request merged**
