### PR TITLE
Script editor web part for a modern page

### PR DESCRIPTION
**Pull request by wobba**
| Q               | A
| --------------- | ---
| New sample?      | yes

#### What's in this Pull Request?

A script editor web part to add arbitrary script or markup to a page. If you have existing scripts, markup or embed code, creating a full SPFx web part might be a bit overkill, instead of just moving the script over to a modern page.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Mikael, will process this over the weekend. Would you be available for doing this as a demo in next Tuesday's monthly community call? - That would be at 5 PM CET (Oslo time) on Tuesday 14th of March. You would have ~15 min to explain the implementation.

**Comment by wobba** [comment]
Sure, send me an invite :)

**Comment by jcoleman-pcprofessional** [comment]
Good stuff, I like your use of the dialog box to prompt for input.  I went a slightly different route and used the property panel for my take on a script editor web part.
https://github.com/jcoleman-pcprofessional/True-Script-Editor

**Comment by wobba** [comment]
@jcoleman-pcprofessional Cool one. I see you're not handling dependencies, and also evaluating script blocks before external scripts are loaded...so the block cannot depend on the externals..right?

And I did think about css loading support as well, and might add that if I need it :)

**Comment by jcoleman-pcprofessional** [comment]
@wobba Good catch, I hadn't considered using both and the impact of such.  Thanks for pointing that out, I'm going to update it to wait for document ready :) .

**Comment by wobba** [comment]
@jcoleman-pcprofessional Hate to be a spoil sport, but that won't work. The document is ready already, and all we do is async after the fact. I did promise chaining in my code to solve this, which is sort of the only way..or nested callbacks when each script is done loaded.

**Comment by jcoleman-pcprofessional** [comment]
@wobba I came to find the same thing, I ended up doing a promise loop with a callback to execute the script editor content (if exists).

**Comment by Danny-Engelman** [comment]
I now do this in a UserCustomAction Scriptlink so all my Scripts and CSS are loaded async and do not cause any render blocking,
And they (usually.. its still async) are loaded before the DOMContentReady event fires.
Since the JS and CSS files (we're doing modern style WebComponent) are loaded from a (sllloowww) SharePoint Library this saves roughly 500ms to sometimes seconds loading time.
(the GetMyProperties endpoint is notoriously slow)

### Question
Does SPFx mean we have to (like what was always the case with jQuery) now again have to wait for a document ready event before we can start pulling in dynamic assets (again..  this is modern W3C WebComponents, so we can't stuff it in with WebPack)

**Comment by wobba** [comment]
@Danny-Engelman No, you can start loading libs in your code at will. But, your part will not start to render/run before the canvas is ready for it. So, the page will be there, and ready. When a SPFx part renders, you get passed in the parent DOM node on which you should render.

**Comment by VesaJuvonen** [comment]
thx Mikael, I'll add also view tracking image on this one, but otherwise good to go.

**Pull request merged**
