### PR TITLE
React Comparer Web Part

### PR DESCRIPTION
**Pull request by hugoabernier**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | None |

## What's in this Pull Request?

New sample demonstrating how to compare two images side by side. Also, implements a fully-featured File Picker that mimics the out-of-the-box SharePoint file picker as a custom (and customizable) property pane control.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @hugoabernier... this one has numerous really useful controls and scenarios presented, even though the actual web part is not necessarily so widely usable... even though the compare image capability is widely used every now and then. I'm especially impressed on the file picker in this one, which we absolutely should include in the PnP property controls as that's really useful for any web part.

Would you be interested in doing a live demo of the used techniques in an upcoming SPFx community call? Would be great stuff for the community.

**Comment by hugoabernier** [comment]
@VesaJuvonen I wholeheartedly agree. The "comparer" part was really an excuse to do a custom file picker. I'd be delighted to demo how I built the file picker.

I'll also open a suggestion on the PnP repo.

**Comment by hugoabernier** [comment]
> Would you be interested in doing a live demo of the used techniques in an upcoming SPFx community call? Would be great stuff for the community.

@VesaJuvonen Yes, I would like to demo on a call. Let me know when and I'll be there.

**Comment by VesaJuvonen** [comment]
That absolutely works - how about 9th of April monthly call as community demo or 11th of April SPFx community call?

**Comment by VesaJuvonen** [comment]
I get that I missed the reply first time, but want to ensure that we get this agreed asap, as SPFx demo spots are currently moving really fast. Hopefully, you can confirm your availability for 9th or 11th asap, so that we get it locked... as getting requests for those spots currently as well.

**Comment by hugoabernier** [comment]
@VesaJuvonen I'd be happy to demo on the 11th if that is still convenient.

Thanks for giving me the opportunity!

**Comment by VesaJuvonen** [comment]
sorry for the delay, let's do that. You'll have a 10-15 min spot in the 11th. Thx.

**Pull request merged**
