### PR TITLE
React msgraph extension

### PR DESCRIPTION
**Pull request by ejazhussain**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?

This sample shows how to managed Microsoft Graph Open Extension in SPFX. This application uses **User** Resource to create Open Extension.

## Features
Here are main features for this application

- Create a new Open Graph Extension
- Get an existing Graph Open Extension
- Update an existing Open Graph Extension
- Remove an existing Open Graph Extension

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Hi Ejaz,

Thank you for sharing this awesome sample! And brilliant job with the README file as well. :)

Would you be interested in demoing this sample in one of our upcoming SPFx community calls? We still have room for demos on the 5th of December, for example.

Laura

**Comment by ejazhussain** [comment]
Hi Laura, 

Always pleasure to share knowledge with amazing community. I love to do demo but i am afraid i wont be available on 5th Dec as i will be in Prague for European SharePoint office 365 conference. 5th Dec is the last day of the conference :)

**Comment by LauraKokkarinen** [comment]
Hi Ejaz,

Oh, cool, see you at ESPC then! :) Would the 19th of December work for you? That's the last SPFx call this year.

Laura

**Comment by ejazhussain** [comment]
Hi Laura,

Yes see you at ESPC 2019. Looking forward for your talk.  Sure 19th December is good for me. 

Thanks
Ejaz

**Pull request merged**
