### PR TITLE
Added Yammer Praise sample

### PR DESCRIPTION
**Pull request by AhmadiRamin**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |

## What's in this Pull Request?

This sample shows how to post a praise to Yammer using aadTokenProvider (without Yammer JavaScript SDK).

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks again @AhmadiRamin for the great sample. As per our chat, I've got you scheduled for the April 23 SPFx call. I look forward to seeing this demoed!

**Comment by AhmadiRamin** [comment]
Thanks Hugo, looking forward to that :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hugoabernier** [comment]
@AhmadiRamin as you may have seem, our latest PnP call experienced some technical difficulties and we had to push all demos by two weeks.

Are you available to demo on May 7th (instead of April 23rd)? 

I really look forward to your demo!

**Comment by AhmadiRamin** [comment]
Hi Hugo,

Noworries, I’m happy to do it on May 7th.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hugoabernier** [comment]
Perfect! I'll update the agenda to show you on May 7th! 

Thanks again for your understanding.

**Pull request merged**
