### PR TITLE
[react-search-refiners] Migrated to SPFx 1.7.0 + Added LUIS Azure Function

### PR DESCRIPTION
**Pull request by FranckyC**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                            |
| New feature?    | yes                              |

## What's in this Pull Request?

* Migrated to SPFx 1.7.0 (Dynamic Data)
* Fixed sort feature
* Removed extension data source. Replaced by SPFx builtin 'page Environment' data source.
* Added a sample TypeScript function to demonstrate NLP processing for the search query
* Miscellaneous improvements

### CODE REVIEW

**Comment by FranckyC** [comment]
@wobba Would it be possible to review the setup on your side to see if everything works well (especially the Azure function part)? I know this is a big reorganization ;) Thanks!

**Comment by wobba** [comment]
I'll look at this as soon as possible.

**Comment by wobba** [comment]
@FranckyC curious why you added another folder inbetween named spfx under react-search-refiners

**Comment by wobba** [comment]
@FranckyC A couple of issues. One, we need to take a dep on ouifr@5.120.0 which is what spfx reusable controls use. If not we get a larger bundle than needed.

Two, you have changed the package and webpart id's - which makes upgrade very hard. Having two parts with the same name is hard. Suggestions?

**Comment by FranckyC** [comment]
Hi @wobba thank you for the review. My bad for the wrong id's. I didn't check since I started from a new project for 1.7.0. Should be fixed now. Also I've create separated folders for the WP code and the Azure function. Since the function is not mandatory, you could only take the WP folder to include in your project. But maybe you thought about an other structure?

**Comment by wobba** [comment]
@FranckyC ahh.. missed the functions folder - then it makes 100% sense. What's the teams folder and manifest? Guess tabs stuff for MS teams - but how does it work? Answer that and I'll merge it :D

**Pull request merged**
