### PR TITLE
Knockout metadata

### PR DESCRIPTION
**Pull request by AJIXuMuK**
| Q               | A
| --------------- | ---
| Bug fix?        | no 
| New feature?    | no
| New sample?      | yes
| Related issues?  | no

#### What's in this Pull Request?

Sample Web Part illustrating
* Reading taxonomy term stores' hierarchy from SharePoint
* Loading JavaScript Object Model scripts
* creating Knockout components

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Alex, we'll have a look on this during upcoming week. Great to get the taxonomy access demonstrated in the samples as well.

**Comment by AJIXuMuK** [comment]
Hello Vesa,

Could you please include company logo on 'December 2016 - Release' page?
[logl](http://www.sharepointalist.com/SiteAssets/logo.jpg)

logo

**Comment by VesaJuvonen** [comment]
thx Alex, image and link to the company page added. Due legal reasons, we need to have explicit permission to do this, but will do this in the future months as well, if you or someone from your company does contributions.

**Comment by AJIXuMuK** [comment]
thanks, Vesa, I appreciate your help!

**Pull request merged**
