### PR TITLE
Added sample: call custom APIs secured with AAD without ADAL JS

### PR DESCRIPTION
**Pull request by waldekmastykarz**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | n/a

#### What's in this Pull Request?

Added sample showing how to call custom APIs secured with Azure Active Directory without ADAL JS

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Waldek, appreciated.

**Comment by Danny-Engelman** [comment]
I have seen a lot and kept my mouth shut,

But can't with this code you are now producing, Waldek, 

even Anders Heijlsberg himself wil smack your for this TypeScript code:

    private renderData(): void {
        if (this.orders === null) {
            return;
        }
        //do something with this.orders
    }


I actually have to work with 'Developers' who 'learn' from these examples,

and they will claim TypeScript doesn't give an error so the code is correct.

And I will smack them

    private renderData(): void {
        if (this.orders) {
            //do something with this.orders
        }
    }

_Delete all examples, keep FIVE, and work on them **together**_

**Comment by VesaJuvonen** [comment]
thx Danny for the feedback. We do accept PRs from the community, so feel free to submit suggestions for the code, if you don't like something. Technically both options are 100% valid and this is more a philosophical discussion on the coding standards, which are different for different companies. 

Now - I do agree that there are samples in the repository, which do require work, but this particular coding pattern is not really the most horrible thing on how community and customers write their code.

"and work on them together" - This is exactly our intention and contributions are more than welcome. thx.

**Comment by Danny-Engelman** [comment]
> and this is more a philosophical discussion on the coding standards, which are different for different companies.

You said it, not me

**Comment by VesaJuvonen** [comment]
Not sure what that comment should mean, but yes I said it. It's true that you should not use return values with void and yes - this can provide a wrong code samples for the field. We all do also mistakes and that's why we absolutely need others in the community to help with these samples. If you find an issue, correction is more than welcome. I can absolutely fix this also based on this input, which is absolutely appreciated.

**Comment by Danny-Engelman** [comment]
Sorry to abuse this thread

My advice is to trim down all those examples, you now have a community where everyone wants to post their own code, there is no community sense at all to correct code.
Yes, I could correct code, but my tone of voice is hardly ever positive, so it won't set an example.

Sent out T-shirt or stickers or whatever for every 5th PR 
and get that community going, because now it is on a road to nowhere.

jQuery was a great example where bad examples went wrong.
The majority of jQuery users have no clue what they are doing.. just see the recent "basic" jQuery issues Waldek is wasting his time on.

So more bad examples attract more bad programmers, causing you more and more support time.
IF Spfx takes off the currect approach certainly won't work.

(*and why do I even care,  I am looking to get out this Microsoft world after 12 Front-End years*)

**Comment by VesaJuvonen** [comment]
Thanks Danny, absolutely valid feedback and good suggestion for the future. We are looking into few different options around this approach, so input appreciated.

**Comment by Danny-Engelman** [comment]
https://www.youtube.com/watch?v=yumZ3tfKVPU

**Comment by darrenparkinson** [comment]
This sample is very much appreciated.  We're not trying to learn React or Typescript with it, but to actually call an AAD secured Web API WITHOUT adal.  I have spent much time trying to work with adal with little success.  I was up and running with this example in a few minutes.  So, thankyou.  One quick question I have though is how to identify the user from the request, specifically in a node.js api -- could you possibly add a node.js example api to the sample showing how this is done?  Thanks again.

**Pull request merged**
