### PR TITLE
React Check User Group membership using Graph API

### PR DESCRIPTION
**Pull request by aakashbhardwaj619**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | NO                               |
| New feature?    | NO                               |
| New sample?     | YES                               |
| Related issues? | NA |

## What's in this Pull Request?

> React Check User Group web part that finds and extracts (to CSV) all the Office 365 or AAD Security groups a user is a member of or all the members present in such a group using Microsoft Graph API. It can be used as an admin utility to quickly check the membership of any user or group from within a SharePoint page itself.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Great stuff again @aakashbhardwaj619 - would you be interested on doing a live demo on this one in one of the upcoming community calls? Great usage of Graph and clean setup.

**Comment by aakashbhardwaj619** [comment]
Thanks a lot @VesaJuvonen, I would love to do the demo...let me know the date :blush:

**Comment by VesaJuvonen** [comment]
Next free spot would be in 26th of March call, if that works for you. Let me know... or then 9th of April.

**Comment by aakashbhardwaj619** [comment]
26th March works fine for me...you can count me in

**Comment by VesaJuvonen** [comment]
Excellent - based on this, you'll be on agenda with this one on 26th. Thanks for this one advance.

**Comment by VesaJuvonen** [comment]
Hi @aakashbhardwaj619 - just a reminder on the community call setup on Thursday this week. Notice that the call is one hour earlier for Europe than typically as the meeting was created in US time zone and they have already moved to summer time.... invite is correct if you have downloaded the recurrent invite.

**Comment by aakashbhardwaj619** [comment]
Thanks for the reminder Vesa...I have the recurrent invite and will be available on scheduled time 😊

**Pull request merged**
