### PR TITLE
Companion sample to js-gitHubBadge sample

### PR DESCRIPTION
**Pull request by hugoabernier**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | Relates to #846  |

## What's in this Pull Request?

This sample accompanies the js-gitHubBadge sample written by @skaggej. It converts the Javascript only web part sample to a React web part.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @hugoabernier, appreciated. Would you and @skaggej be interested on doing a live demo discussion around this web part and the steps to convert the js library one to use React... kind of learnings from that work. Why would you do that and technical steps.

**Comment by hugoabernier** [comment]
@VesaJuvonen I'd be happy to, provided that @skaggej is open to it.

**Comment by skaggej** [comment]
@VesaJuvonen, that would be great! I'm in!

**Comment by VesaJuvonen** [comment]
Awesome - would both of you have availability for this on 23rd of May? That would be typical timing with 7 AM PST. Works?

**Comment by skaggej** [comment]
I'll be in Vegas at the SharePoint conference, so might be tricky. Will you be there? Is the PnP team doing anything "live from Vegas?"

**Comment by VesaJuvonen** [comment]
I'll be in Vegas as well... doing live from Vegas is tricky due to 7 AM morning setup... so no - we are not planning to do anything specific there for that. If that does not work, we can absolutely push it for 2 weeks, if that's fine? That would be 6th of June.

**Comment by skaggej** [comment]
I took a look over my schedule and both the 23rd of May and 6th of June work for me. I'll make either one work!

**Comment by hugoabernier** [comment]
June 6 works for me. We'll see you all in Vegas, though!

**Pull request merged**
