### PR TITLE
Upgrade to SPFX RC0

### PR DESCRIPTION
**Pull request by russgove**
| Q               | A
| --------------- | ---
| Bug fix?        | no - yes?
| New feature?    | no - yes?
| New sample?      | no - yes?
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Please describe the changes in this PR. Sample description or details around bugs which are being fixed.

#### Guidance
*You can delete this section when you are submitting the pull request.* 
* *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
* *Please target your PR to 'dev' branch.*

Thanks for your contribution! Sharing is caring.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Russell, appreciated.

**Comment by VesaJuvonen** [comment]
and just noticed again one big issue right after merged - this one is completely missing again pictures - so there's breaking rendering on the readme. Would appreciate if you'd push the pictures back, since otherwise others would now know how the web part works or look like. Thx.

**Comment by VesaJuvonen** [comment]
Hi Russell, 
Just to follow up on the pictures / images. I'll add these manually personally, if needed, but right now readme is with broken images since they were not included in the latest updates.

**Comment by russgove** [comment]
hi vesa,
i am on vacation this week, but will be sure to clean up the readme files when i return on saturday
russell

**Pull request merged**
