### PR TITLE
React-Tree-Organization-Chart

### PR DESCRIPTION
**Pull request by joaojmendes**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
 
 
| New sample?     | yes                              |
 

## What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> New WebPart - React-Tree-Organization-Chart

## Guidance

> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
> 
> *Please target your PR to `dev` branch. Released documents are in `master` branch.*
>

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @joaojmendes, nice and clean setup demonstrating important topics like following:

- PnPjs usage
- Graph
- Controls

Would you be interested on doing a live demo of this in any of the upcoming SPFx community calls?

**Comment by joaojmendes** [comment]
thank you @VesaJuvonen . Yes I'm , please let me know the date to book it.
Thank you.

**Comment by VesaJuvonen** [comment]
Hi Joao, we would have a spot for 28th of March call or then for the next one on the 11th of April. Either one works currently. Let me know what works for you. Thx.

**Comment by joaojmendes** [comment]
Hi Vesa, Thank you for the invite. 28th of March is ok for me. Thank you .

**Comment by VesaJuvonen** [comment]
thx @joaojmendes - just confirming the 28th... we will have 3 demos for that week, so 10-15 is the time booking - definitely not longer than that... Thanks for volunteering.

**Comment by joaojmendes** [comment]
Thank you very much. To give me opportunity to  participate.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
