### PR TITLE
react-graph-reports solution has been added

### PR DESCRIPTION
**Pull request by ejazhussain**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |

## What's in this Pull Request?

> This sample describe a SPFX application which reterive an office 365 usage reports using Microsoft Graph API. This application also use chartjs library to generate graph.

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Thanks a lot for your contribution, Ejaz! The web part looks awesome! :)

I modified the README slightly: added the missing telemetry image, and added a couple of steps on how to approve Graph permissions just in case someone doesn't know how to do it.

Thanks again and keep up the good work!

Laura

**Comment by ejazhussain** [comment]
> Thanks a lot for your contribution, Ejaz! The web part looks awesome! :)
> 
> I modified the README slightly: added the missing telemetry image, and added a couple of steps on how to approve Graph permissions just in case someone doesn't know how to do it.
> 
> Thanks again and keep up the good work!
> 
> Laura

Thanks Laura for adding missing information to the README file.

**Comment by ejazhussain** [comment]
Hi Laura,

Just checking when does samples move from Dev branch to master branch?

Seems like this sample still sits under dev branch.

Regards
Ejaz

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LauraKokkarinen** [comment]
Hi Ejaz,

Vesa did the master merge at the end of last week, so your sample can now be found under the master branch. Sorry about the delay and the late reply!

Laura

**Comment by VesaJuvonen** [comment]
Hi @ejazhussain, would you be interested on doing a live demo of this in upcoming SPFx calls? This is really nice sample which demonstrates the Graph usage pattern and also how to use external library - this case the chart.js. We would have a spot still next week SPFx call on 23rd of May or then next one on 6th of June, depending on your availability.

**Comment by ejazhussain** [comment]
Hi @Vesa Juvonen<mailto:notifications@github.com>. Happy to do the live demo. I can do 23rd May.

Regards
Ejaz Hussain
________________________________

**Comment by VesaJuvonen** [comment]
Sounds good, I'll add you for the agenda for the 23rd of May. Thanks for volunteering.

**Pull request merged**
