### PR TITLE
React twitter

### PR DESCRIPTION
**Pull request by AJIXuMuK**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | no |

## What's in this Pull Request?

Sample web part to display Twitter timeline.

This sample illustrates how to use [react-twitter-embed](https://www.npmjs.com/package/react-twitter-embed) module to display Twitter timeline of specific profile, likes, list, collection or url.
It also uses [PnP React Controls](https://github.com/SharePoint/sp-dev-fx-controls-react) and [PnP Property Controls](https://github.com/SharePoint/sp-dev-fx-property-controls) for rich web part and property pane components.

The sample is related to the discussion in [PnP React Controls repo](https://github.com/SharePoint/sp-dev-fx-controls-react/issues/461)

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Nice work on this @AJIXuMuK - any change you'd be interested on doing a live demo on this in the upcoming community call? We would have next free spot on 12th of March SPFx call if you have availability or later works as well.

**Comment by AJIXuMuK** [comment]
Thanks @VesaJuvonen!
Will be happy to demo. It will be a pretty short demo as there are literally few lines of code :)

**Comment by VesaJuvonen** [comment]
Sounds good - 5 min demos are always also welcome. It's indeed quite simple, but also demonstrates the simplicity of using existing packages on the SPFx solutions, so let's focus on that and also on the web part options vs oob experience.

**Comment by AJIXuMuK** [comment]
Then March 12th it is!

**Pull request merged**
