### PR TITLE
Add sort panel

### PR DESCRIPTION
**Pull request by stijnbrouwers**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | yes                               |
| New sample?     | no                               |
| Related issues? | / |

## What's in this Pull Request?

An extra panel so the user can apply sorting to the list.

## Guidance

- Changing the properties of the webpart and setting SortList still has the same behaviour. (Sorting the list when entering the page).
- When changing the properties of the webpart (screen 2 of 3) an extra field is available to set the list of fields available to the user for sorting the search results (format is the same as the format for adding refinement fields)
- When sortable fields are available, an extra button will appear on the results webpart (next to the filter icon, there now should be a sort icon)
- The user can click the sort icon to popup the new sort panel
- The user can now select the field to sort the list on and the sort order (ascending/descending)

### CODE REVIEW

**Comment by FranckyC** [comment]
Thank you for this PR @stijnbrouwers! This is a great feature. Few things I see at first glance:
- The initial WP instanciation fails (local/hosted):

image

- README documentation is missing
- Scenario when a managed property is not sortable not supported. Try with "FileType", the WP fails silently and get stuck forever.

Please fix these issues first and let me know.

**Comment by stijnbrouwers** [comment]
@FranckyC thanks for the quick feedback. I fixed the 2 issues, I only need to change the readme file. I will do that later, but what exactly are you expecting in the README file?
- Change the screenshots of the property pane
- Add the extra fields to the 'Search Settings' table
Is there anything else I'm missing that you would expect?

**Comment by FranckyC** [comment]
@stijnbrouwers Yes, just fill the parameter table accordingly and provide hints about how this option works.

**Comment by FranckyC** [comment]
@stijnbrouwers Thanks for updates. Would it be possible for you to merge your things with the latest version of this WP. I've made some updates today that have been merged in the dev branch already. This way, the PR review will be easier to review.

Thanks!

**Comment by stijnbrouwers** [comment]
@FranckyC Working on it right now :-) Am testing the merge but had some trouble...  hope to finish it today!

**Comment by stijnbrouwers** [comment]
@FranckyC I'm putting this on hold for now...
For Some reason when merged, I can't have 2 panels.
One I add even an empty panel for the sort, the one for the filters won't open anymore...

**Comment by FranckyC** [comment]
@stijnbrouwers no worries. Just let us know when it will be ready

**Comment by stijnbrouwers** [comment]
@FranckyC Allright, it should be OK now!

**Comment by FranckyC** [comment]
@stijnbrouwers seems ok except:
- Missing localizations in **SortPanel.tsx**
- Please reset the `hasError` state in `componentReceiveProps` in `SearchResultsContainer.tsx`. When there is an error on sortable fields, the user can't revert back easily otherwise.

```
    public async componentWillReceiveProps(nextProps: ISearchContainerProps) {

        let query = nextProps.queryKeywords + nextProps.searchService.queryTemplate + nextProps.selectedProperties.join(',');

        // New props are passed to the component when the search query has been changed
        if (JSON.stringify(this.props.refiners) !== JSON.stringify(nextProps.refiners)
            || JSON.stringify(this.props.sortableFields) !== JSON.stringify(nextProps.sortableFields)
            || this.props.sortList !== nextProps.sortList
...
```

- I would rename the `SortOrder` class to `SortDirection` because it is pretty misleading in the code (this is not really an "order"). You have a `SortDirection` class already available form PnP, maybe you can reuse this one at some point.

- You have a typo in `_onUpdateSort` preventing sort direction to work. Use lower case `sortOrder` instead.
```
this.props.searchService.sortList = `${sortField}:${SortOrder}`;
```

**Comment by stijnbrouwers** [comment]
@FranckyC OK the changes should be implemented. I just wasn't sure what to do for the second remark (componentReceiveProps) but I did what I think you requested.

**Comment by FranckyC** [comment]
Thanks @stijnbrouwers. @wobba I think it is ok, you can review it if you want and merge it works for you.

**Comment by wobba** [comment]
@stijnbrouwers  Looking at the PR it seems my last commit is not included (checked the readme) Could you do a last merge with the dev branch, and I’ll review and merge most likely on Monday.

**Comment by stijnbrouwers** [comment]
@wobba I just merged it, thanks for reviewing and have a nice weekend!

**Pull request merged**
