### PR TITLE
add react-pnpjs-project-online sample

### PR DESCRIPTION
**Pull request by joelfmrodrigues**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                                |
| New sample?     | yes                               |
| Related issues? | No |

## What's in this Pull Request?

New sample using a custom PnPjs module to interact with Project Online

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Nice tech demo on the pnpjs project library. Would you be interested on doing a live demo of this and the project library in any of the upcoming community calls?

**Comment by joelfmrodrigues** [comment]
Hey Vesa, sure. Let me know when there is a slot available.

**Comment by VesaJuvonen** [comment]
Next free spot would be 19th of September for the SPFx calls. Following then on 2nd of Jan and 16th of Jan... each call has already other demos, so booking early is good. Let me know.

**Comment by joelfmrodrigues** [comment]
2nd of January if possible please, but 16th should also be fine.

**Comment by joelfmrodrigues** [comment]
My bad, I'm not available on the 16th January as I will be at MS Ignite The Tour - London

**Comment by VesaJuvonen** [comment]
Thanks @joelfmrodrigues, let's book you for the 2nd of January based on this one. Thanks for volunteering. I'll send the invites out in the social media few days before.

**Pull request merged**
