### PR TITLE
fixed a broken link on readme file

### PR DESCRIPTION
**Pull request by giuleon**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | no

#### What's in this Pull Request?

Fixed a broken link on readme file

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Giuliano, appreciated.

**Comment by VesaJuvonen** [comment]
On this and the other sample which you submitted. Would you be interested in doing a live demo in tomorrow's SPFx community call around these? - Call is on 7 AM PT and you'd get 10-15 min spot to demonstrate shared samples, based on your availability.

**Comment by giuleon** [comment]
Sorry Vesa tomorrow I can't, but really thank you for the opportunity I'm honored and totally available next call if you still have a free slot for me.

**Comment by VesaJuvonen** [comment]
thx Giuliano, will try to make that happen in future. Thanks for volunteering.

**Comment by giuleon** [comment]
It's a pleasure and a passion, thanks Vesa.

**Pull request merged**
