### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by taraldga**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | yes                               |
| New sample?     | no                               |
| Related issues? |  |

## What's in this Pull Request?

> New feature for the react-search-refiners webpart. This webpart now supports the use of custom code renderers. A simple instruction on how to get started is included in the documentation, and a seperate sample with full implementation documentation will be in a upcoming, seperate PR.

### CODE REVIEW

**Comment by wobba** [comment]
@taraldga Can you switch the guid code to use `import { Guid } from '@microsoft/sp-client-base';` instead?
`var guid: Guid = Guid.newGuid();`

**Comment by taraldga** [comment]
@wobba It seems that 'sp-client-base' is no longer scaffolded in SPFx solutions, and are not containing the Guid Class anymore. The guid generated here is not very important, it could be anything that is guaranteed unique from other webparts that use the same generator.

**Comment by wobba** [comment]
Thank you @taraldga. This will be awesome. @FranckyC feel free to take a peek, and we'll add a sample render project soon as well.

**Comment by FranckyC** [comment]
Thanks @wobba and @taraldga! I will take a look ASAP. Not a big deal but I've just noticed image links seem to be broken in the README file.

**Comment by wobba** [comment]
@FranckyC images were .PNG so I fixed the casing in readme (easier then renaming the files) cc @taraldga

**Comment by FranckyC** [comment]
@wobba Should be better with a test project to demonstrate how to use this. Even after reading the doc it is still quite unclear for me :(. Maybe a separated .md file to explain all steps would be useful because I'm not sure everybody will see the gain at first glance.

**Comment by wobba** [comment]
@FranckyC indeed and @taraldga is in the process of submitting that. Figured we'd get the code in first to ease merging when you commit more stuff :) And  the .md's will link.

**Pull request merged**
