### PR TITLE
Added new sample react-manage-o365-groups

### PR DESCRIPTION
**Pull request by nanddeepn**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                                |
| New sample?     | yes                               |
| Related issues? | |

## What's in this Pull Request?
Added new sample react-manage-o365-groups

## Guidance
We can view and manage your own O365 groups in Outlook on the web.
This SPFx solution goes beyond this limitation and provides below functionalities using MS Graph APIs:

1. List all public and private groups with basic information (name, description, privacy, logo, etc.)
2. Search the group
3. Join and leave public groups
4. Join a private group with approval of group administrator (using Power Automate flow) and leave the private group
5. Manage group link for administrators
6. Browse MS Teams associated with group
7. Set up new group

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Great work @nanddeepn and Smita on this one, really looks nice. Would you be interested on doing a live demo in one of the upcoming community calls around this? 15 min to cover the functionality, code and learnings. Works?

**Comment by nanddeepn** [comment]
Hi @VesaJuvonen ,
Thank you very much.
We would be really interested to demo this during upcoming community calls.

**Comment by VesaJuvonen** [comment]
thx @nanddeepn, we would have next free spot current in the 27th of Feb call. I get that it's quite far, but there's growing demand for the demos, which explains the wait times. Happy to book you for that one now, if that works.

**Comment by nanddeepn** [comment]
Hello @VesaJuvonen, 
I can understand the waiting time. That's the power of community.
27-Feb slot will do for us. Thank you!

**Comment by VesaJuvonen** [comment]
Excellent - thanks for confirming so fast, have added you for the agenda of 27th of Feb call. If there's any changes on your availability before the call, please let us know. We'll push out the agenda few days before the call.

**Comment by nanddeepn** [comment]
Sure. Thank you @VesaJuvonen

**Pull request merged**
