### PR TITLE
added the org chart web part

### PR DESCRIPTION
**Pull request by vman**
| Q               | A
| --------------- | ---
| Bug fix?        | no 
| New feature?    | no
| New sample?      | yes

#### What's in this Pull Request?

Please describe the changes in this PR. Sample description or details around bugs which are being fixed.

Added the Organisation Chart sample webpart

### CODE REVIEW

**Comment by vman** [comment]
Closing this PR as I have updated the web part and created another pull request: https://github.com/SharePoint/sp-dev-fx-webparts/pull/14

**Comment by hugoabernier** [comment]
✅ PR affects only one sample file.
❌ PR does not contain a `.nvmrc` file.
❌ Sample does not contain a `README.md` file.
❌ `README.md` does not contain a  visitor stat tracking image

**Comment by hugoabernier** [comment]
✅ PR affects only one sample file.
❌ Sample is not named correctly.
❌ PR does not contain a `.nvmrc` file.
❌ Sample does not contain a `README.md` file.
❌ `README.md` does not contain a  visitor stat tracking image

**Comment by hugoabernier** [comment]
✅ PR affects only one sample file.
❌ Sample is not named correctly.
❌ PR does not contain a `.nvmrc` file.
❌ Sample does not contain a `README.md` file.
❌ `README.md` does not contain a  visitor stat tracking image

**Pull request closed without merging**
