### PR TITLE
Upgrade react-Securitygrid to 1.9.1

### PR DESCRIPTION
**Pull request by russgove**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no - yes?                               |
| New feature?    | no - yes?                               |
| New sample?     | no - yes?                               |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

## Guidance

> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
> 
> *Please target your PR to `dev` branch. Released documents are in `master` branch.*
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Hi @russgove ,

Could you please describe what is included in this PR? You can find more information about our contribution guidelines at https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/.github/CONTRIBUTING.md

Thanks!

Laura

**Comment by russgove** [comment]
Hi, this was updated to spfx 1.9.

i'll have another update with better functionality in a few weeks.

**Comment by russgove** [comment]
oops,  no , this inludes enabling multiple permissions, color coding and icon for separate permissions. it addresses questions raised by @mikezimm

**Comment by russgove** [comment]
https://github.com/SharePoint/sp-dev-fx-webparts/issues/1081#issuecomment-564569475

**Comment by russgove** [comment]
Hi, Can this PR be merged.

**Comment by russgove** [comment]
@LauraKokkarinen , Can we get this merged?

**Comment by hugoabernier** [comment]
Hey @russgove thanks for your patience as we're going through the backlog of pull requests.

This is a great sample, but I'm getting some warnings and errors when I'm testing it.

Do you mind taking a look at the following issues and updating your pull request?
* I'm getting a `Error - [tslint] No valid rules have been specified for TypeScript files`. The previous version seemed to work without issues. Can you take a look at what could be wrong?
* It doesn't look like you use `SpSecurity.scss` anywhere. It causes a `filename should end with module.sass or module.scss` warning which may throw off people who are new to SPFx/React
* I would encourage you to avoid any CSS that begin with `ms-` as it could override the styles globally. You can use a specific CSS selector like `.SPFXSecurityGrid .ms-...` as you do in `SpSecurity.scss`. If you use a `.module.scss`, you can use:
```css
.SPFXSecurityGrid {
    :global(.ms-...) {
        ...
    }
}
```
* Do you mind if we remove the `upgrade-report.md`?
* Your `readme.md` should be updated to reflect that it uses SPFx 1.9.1; this will make it easier for people to find your sample

This is a great sample with a beautiful UI! I can't wait to see this sample in the `master` branch. If you submit your changes, I'll make sure to process your PR as quickly as possible.

**Comment by russgove** [comment]
Hi Hugo,
Thanks for the tslint tip. I fixed that and all the resulting tslint errors. 

The css stuff needs to stay the way it is. I am puposefully overiding the ms- classes to get the headers to display at angles.

Please let me know if you need anything else. 
Russell

**Comment by hugoabernier** [comment]
Thanks @russgove, this looks great! 

Did you ever get to present this web part on a PnP SPFx call? If not, would you be interested in demoing it on a future call?

**Pull request merged**
