### PR TITLE
React Check Flows associated to a SharePoint List

### PR DESCRIPTION
**Pull request by aakashbhardwaj619**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | na |

## What's in this Pull Request?

React Check Flows SPFx web part that displays the automated flows associated with the selected list in a SharePoint Site.

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Hi @aakashbhardwaj619 ,

Thank you for this handy web part sample! :) Certainly makes it easier to check if the lists on the site have Flows attached to them.

Laura

**Comment by aakashbhardwaj619** [comment]
Thanks for approving the PR Laura :) Really happy to contribute to the community and appreciate the good work you all are doing.

**Comment by LauraKokkarinen** [comment]
Hi @aakashbhardwaj619 , and absolutely no problem! Thanks for contributing. :)

Would you be interested in doing a community call demo about this and the page navigator sample you contributed a little while ago? We could reserve you a 20-minute slot e.g. in the call next week? (the 10th of October).

Laura

**Comment by aakashbhardwaj619** [comment]
Hi Laura,

I'm interested in doing the demo :)

Regards,
Aakash Bhardwaj

**Comment by LauraKokkarinen** [comment]
Excellent! I'll note down that you'll be one of the presenters next week then! Mark the 10th of October in your calendar. ;)

Laura

**Comment by aakashbhardwaj619** [comment]
Thanks Laura. I'll be available on the 10th :)

I just noticed there was a small issue with the links sorting order in the page navigator sample so I'll be opening a new PR with its fix today.

**Pull request merged**
