### PR TITLE
Teams personal app settings

### PR DESCRIPTION
**Pull request by AJIXuMuK**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                              |
| New sample?     | yes                               |
| Related issues? | no |

## What's in this Pull Request?

Sample web part that demonstrates how you can store Teams Personal App Web Part's properties in user's OneDrive.

### CODE REVIEW

**Comment by hugoabernier** [comment]
@AJIXuMuK this looks like it is going to be an awesome sample.

Would you mind making a few tweak before we accept the PR?
- You seem to have a few changes to the `react-officegraph` sample... was that intended?
- Would you mind providing a little bit of info on how to deploy/use the solution? (i.e.: the `## Minimal path to awesome` section
- Can you include a screen shot of the web part?

I look forward to accepting this PR... and you know what question comes next, right?

Would you like to present this sample at an upcoming SPFx community call? We have an opening on June 18th.

**Comment by AJIXuMuK** [comment]
Hey @hugoabernier!
I pushed the changes you asked for. Sorry for not providing the image and minimal path to awesome right away.

Regarding changes in `react-officegraph` - it looks like really old change that lived in my `master` branch related to line endings.

If it's a an issue, I can re-fork the repo and copy my changes to the new forked repo.

**Comment by AJIXuMuK** [comment]
And I'm open for June 18 :)

**Comment by hugoabernier** [comment]
Thank you @AJIXuMuK, it's always a pleasure to review your samples.

As discussed, I have you scheduled for June 18th. Looking forward to see your demo!

**Pull request merged**
