### PR TITLE
Updated the solution to SPFx version 1.10.0

### PR DESCRIPTION
**Pull request by Harshagracy**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                               |
| New feature?    | no                             |
| New sample?     | no                              |
| Related issues? | #1144 #1137  |

## What's in this Pull Request?

Updated the solution from 1.4.1 to 1.10.0 version and fixed the issue in the constructor

### CODE REVIEW

**Comment by wobba** [comment]
I'm fine with constructor fix, but not SPFx upgrade as it removes on-prem support. v1.4.1 is needed for on-prem, and nothing in this web part requires a newer version. Also, would be nice if Readme etc was not causing a diff, as it makes it hard to review if changes were made.

**Comment by Harshagracy** [comment]
Thanks @wobba for your valuable feedback. I will keep these things in mind when I submit again. :)

**Comment by wobba** [comment]
I will actually split the sample into two parts for some other scenarios - having one targeted at 1.10. Expect this work by start of next week.

**Comment by VesaJuvonen** [comment]
Thank you @Harshagracy  for this contribution, we really value it and it started internal discussion to the right model for the web part. We'll definitely call out you as a contributor on the monthly summary and in our monthly community call based on this. We did agree that @wobba will do the needed edits for now for this one to make two different versions and feel free then to modify them as needed... 

Thank you for pushing us forward on doing this redesign, really really helpful.

**Comment by Harshagracy** [comment]
Thanks, @VesaJuvonen and @wobba .

**Comment by Harshagracy** [comment]
Hi @wobba , I have the solution ready and working for SPFx 1.10 already. Please let me know if I can submit that.

**Comment by wobba** [comment]
@Harshagracy I'm changing a few other settings, so no need. Want to test a few things before I commit.

**Comment by wobba** [comment]
@Harshagracy If you edit the page, save, then edit.. etc.. do you see loading of the edit mode on try #2? Seems to be an issue and think it's related to React perhaps v16, compared to v15 in the prev version. You can try it in the hosted workbench as well.

**Comment by wobba** [comment]
@Harshagracy  figured it out :)

**Comment by wobba** [comment]
@Harshagracy code is in and feel free to give it a spin :)

**Comment by Harshagracy** [comment]
@wobba That's awesome 👍

**Comment by arunkumarperumal** [comment]
@wobba , Seems like the web part after this fix is not showing in the web part listing on a modern communication site. Works fine on workbench. Checking to see if i can have it fixed. Can you please let me know if it works on your end.

**Comment by wobba** [comment]
@arunkumarperumal and you have gone thru the options needed to make it work on a modern site? https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-script-editor#deploy-to-non-script-sites--modern-team-sites or enable scripting for the site.

**Comment by arunkumarperumal** [comment]
@wobba good to know, earlier version of the app didn't have requiresCustomScript forced to true. Thought the idea of this app was to use existing javascript solutions to work on modern page. Anyways, works now after changing the property for the web part.

**Comment by wobba** [comment]
I'm pretty sure they all had `requiresCustomScript:true`, and I can check the commit logs to verify ;) Since the web part does have custom scripting, it's set to this by default. Using the web part is an easy migration path, but potentially a big security whole if people add malicious script to it not verified by an admin.

**Pull request closed without merging**
