### PR TITLE
react-my-groups sample zachdev

### PR DESCRIPTION
**Pull request by zachroberts8668**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | no                                |
| New sample?     | yes                             |
| Related issues? | no|

## What's in this Pull Request?

New sample that uses Microsoft Graph to grab the current user's Office 365 groups, the groups are listed out and when clicked they link to that groups SharePoint site. The web part also grabs the thumbnail images of the groups for use in the layout.

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Hi Zach,

Thank you for this sample! I know for a fact that there are many customers who want to show these kinds of lists in their SharePoint environments. I'm sure this web part will be used by many. Cheers! :)

Laura

**Comment by LauraKokkarinen** [comment]
Hi @zachroberts8668 , 

Would you be interested in doing a short demo about this sample in one of our upcoming SPFx community calls?

Laura

**Comment by zachroberts8668** [comment]
Hi @LauraKokkarinen ,

Yes, I would be happy to do a demo.

Thanks,
Zach

**Comment by LauraKokkarinen** [comment]
@zachroberts8668 Excellent! :) Would you be available for a 10-15 minute demo during the call on the 24th of October or the 7th of November?

Laura

**Comment by zachroberts8668** [comment]
@LauraKokkarinen November 7th works for me :)

Thanks,
Zach

**Comment by LauraKokkarinen** [comment]
Great, I've marked a spot for you! :)

Laura

**Comment by LauraKokkarinen** [comment]
Hi @zachroberts8668 ,

I'm so sorry, but I'll have to cancel/reschedule your demo: It was just decided that we'll do some kind of an "Ignite special" call on the 7th of November and will not have any demos on that community call. Would you be ok doing the demo on some other date? We still have room e.g. on the call on the 24th of October.

Laura

**Comment by zachroberts8668** [comment]
Hey @LauraKokkarinen ,

What time do you usually do the community calls at? I will let you know if I can make it on the 24th but if not I am willing to demo on another date! Thanks for the heads up! 😄

-Zach

**Comment by LauraKokkarinen** [comment]
Hi @zachroberts8668 ,

You can download the community call calendar invite from https://aka.ms/spdev-spfx-call to see what time it occurs exactly in your time zone.

If the 24th doesn't work for you, the next call after Ignite is on the 21st of November. It'd be great to have you already on the 24th though if at all possible. :)

Laura

**Comment by zachroberts8668** [comment]
@LauraKokkarinen ,

Sorry for the late reply but I was not able to make it on the 24th. However I can be available for the call on the 21st of November.

Thanks,
Zach

**Comment by LauraKokkarinen** [comment]
Hey @zachroberts8668 , and no worries! :) I'll note you down for the 21st of November. Thanks a lot for being willing to present!

Laura

**Comment by VesaJuvonen** [comment]
Just a reminder on this - hopefully we are good for the demo today in the community call within 1.5 hours.

**Comment by VesaJuvonen** [comment]
Also @zachroberts8668  - can you provide your full name, so that we can credit you using your actual name and potentially your company. This way we can truly call you out using your full credentials in the externally facing messaging. Thanks.

**Comment by VesaJuvonen** [comment]
Actually - I think I found you based on the tweets - https://twitter.com/ZachSPODev. If you want your company to be called out, please do share. Thx.

**Comment by zachroberts8668** [comment]
Hi @VesaJuvonen , Yea that is me you found on twitter 😊. Full name is Zachary Roberts though I usually go by Zach. I will be there for the demo today.

**Pull request merged**
