### PR TITLE
Add tslint at the root of each SPFx project

### PR DESCRIPTION
**Pull request by joelfmrodrigues**
| New feature?    | Yes

#### What's in this Pull Request?

Added tslint.json configuration file to the root folder of each web part. This file is only to instruct VS Code TSLint extension with the correct location to get the TSLint rules from.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
I did saw your blog post and we absolutely should get this fixed by default in the Yeoman template. Since there's though not really harm on getting the instruction redirection there, this is suitable setup, even though the tslint would not be globally installed. Thx for your contribution.

**Comment by joelfmrodrigues** [comment]
Thanks @VesaJuvonen , the VSCode extension speeds up development a lot as we don't need to wait for the command line to build and flag errors. It also gives us the option to click on the error and jump straight to that line of code which I find extremely helpful.

**Comment by andrewconnell** [comment]
What about the `tslint.json` in every `config` folder? Doesn't this dupe?

**Comment by joelfmrodrigues** [comment]
@andrewconnell in my opinion the best option would be to move the tslint.json file to the root of the working folder, but this should ideally be done by the yeoman generator and will probably require small changes to the build task when running tslint. 
Creating a new tslint.json file at the root with "rulesDirectory": "./config" was the easiest/cleanest option that I found, but if you have a better option, I'm listening :)

**Comment by andrewconnell** [comment]
Seems like having one in the root that points to a nested one is excessive IMHO... why not just move the one from `config` to the root? Matter of preference I guess.

Honestly I'd rather `tslint.json` it not be there at all, but I've said my peace on that https://github.com/SharePoint/sp-dev-docs/issues/653#issuecomment-313697756

**Comment by joelfmrodrigues** [comment]
Agree, this is just a workaround until (fingers crossed) the generator is updated to create the tslint.json file at the root.
I don't particularly agree with you on dropping the tslint config file as I don't see any issue with MS providing a default config that can be easily changed. It can actually be a good thing for projects like PnP, so that all projects are configured the same and switching between projects is extremely easy -
 without requiring people to agree default rules, which would be almost impossible :D
I would have a heart attack if someone decided to use 3 spaces instead of 2 or 4 or tab

**Pull request merged**
