### PR TITLE
New sample - CSS in JS with TypeStyle.

### PR DESCRIPTION
**Pull request by s-KaiNet**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | yes                               |

## What's in this Pull Request?

A new sample, which demonstrates how to use SharePoint Framework and "CSS in JS" pattern using TypeStyle library.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks @s-KaiNet, this is a great sample! I have a feeling I'll be using this pattern in many of my future applications.

Can you confirm that this is the sample for the demo you'll be presenting on June 4th?

**Comment by s-KaiNet** [comment]
Right, this is for the demo on June 4th (long waiting queue for a demo, but it's great that so many people want to share their web parts/patterns with SharePoint Framework!).  
Later on Andrew @koltyakov will add a sample with [styled-components](https://styled-components.com/), which is an alternative approach (a bit more advanced). That way we're going to cover this topic in details on June 4th.

**Comment by StfBauer** [comment]
As great that it is to have as many examples of things that are available at the wild. Great work - @s-KaiNet 

But it also likes to mention that CSS-in-JS could lead to a performance impact and tends to be removed in future because of that performance impact.

> Runtime performance. Improve render speed by leveraging CSS variables to avoid costly CSS in JS computation overhead. [UI Fabric evolving to Fluent UI](https://github.com/microsoft/fluentui/issues/12288#issuecomment-601834743)

**Comment by s-KaiNet** [comment]
That's right, when used wrongly it might lead to performance issues. You should understand how it works in order to avoid this issue. 
When it comes to my sample here, I don't have any performance problems, because
 - computations are fast
 - computations happen only on startup or when a theme changes, not on every render

Do you mean removed from UI Fabric? Maybe, I don't know how they use it. 
If you mean removed from the internet, then I don't agree, because a lot of big companies use CSS in JS approach and they do care about performance (airbnb, lyft, patreon to name some.)

**Comment by Harshagracy** [comment]
@StfBauer : That means it is recommended to use CSS variable in the code, rather than binding it after the component is present in the DOM?

**Comment by s-KaiNet** [comment]
CSS variables is a great thing and you should use it. However CSS vars and CSS in JS are not mutually exclusive, you can use both approaches.

**Comment by StfBauer** [comment]
@Harshagracy when you don't have support IE11 you can use a CSS variable.
@s-KaiNet removed from Intranet - No
removed from Office UI Fabric - Yes because of the high computation cost compared to plain CSS.  CSS is optimised in the browser while CSS-in-JS is not optimised and only loads once CSS and HTML are established. The time the package is loaded on the page milliseconds later the CSS is already on the page.

In JSS or JavaScript, the code is still processing and processes more cause it gets an additional hit by the included CSS:
Sure it computes only on startup but it computes while CSS is already computed.

Sure, Airbnb, Lyft, Patreon use it but they don't tell you where and for what. Marketing does a good job to promote but that is not wise for technical decisions. ;) Honestly, I always wonder this company use this and this and this. Microsoft uses ReactJS, Angular, VueJS - which one should I choose then. The even use plain CSS, CSS-in-JavaScript, SASS, .... cool I must use all this too. ;) I guess you get my point.

**Comment by s-KaiNet** [comment]
Well, like I mentioned in the blog post, the topic is very debatable :)   

There are a lot of people who prefer one approach over another. However, the thing is, that we can not ignore CSS in JS today, because it's so widely used. Not only by big companies but by developers as well. You can see downloads number, github stars. Developers, like you and me, always consider different aspects of a library before using it. If we sum the downloads of some top CSS in JS libraries, they will beat `node-saas`. For me, it matters, at least to try it and see how it performs.

> Microsoft uses ReactJS, Angular, VueJS - which one should I choose then   

The answer is simple - you shouldn't use knockout 😄

**Comment by StfBauer** [comment]
You mean tiny compared to node-sass - If you want to go that route 😃

image
image

**Comment by koltyakov** [comment]
CSS in JS is larger, it's not a specific library you mentioning.

image

node-sass is kinda library which cause many issues and on the way being replaced with dart sass (a pure JS implementation) in many projects, but this is a completely different story:

image

**Comment by s-KaiNet** [comment]
emotion also worth mentioning: 
image  

sass will be bigger in "Used by" simply because it's older:

image

Let's back to this talk in 2 years 😉

**Comment by s-KaiNet** [comment]
> Let's back to this talk in 2 years  

When everybody will use WebAssembly 😂

**Comment by Harshagracy** [comment]
Thanks @stfbauer. Got to learn new stuff today from all of your conversation.

**Comment by StfBauer** [comment]
@s-KaiNet @koltyakov You mean when it was once a huge thing 😜

**Comment by s-KaiNet** [comment]
@StfBauer was once? 😊  


image

**Comment by hugoabernier** [comment]
@s-KaiNet, @koltyakov, @StfBauer samples such as these are important to show the community various ways to solve problems.

It sounds like it would a great opportunity to create a similar (if not identical) demo that demonstrates your preferred approach and give the community the opportunity to compare. 

I know I certainly could learn a lot from the three of you!

We should absolutely continue this conversation in the [issues](https://github.com/SharePoint/sp-dev-fx-webparts/issues/new) list and let others weigh in.

**Comment by s-KaiNet** [comment]
yeahh.. let's stop it here, otherwise, it might last forever :)

**Comment by hugoabernier** [comment]
I'm looking forward to see PRs for comparable solutions though :-)

**Pull request merged**
