### PR TITLE
React image gallery

### PR DESCRIPTION
**Pull request by ejazhussain**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no   |
| New feature?    | no  |
| New sample?     | yes |

## What's in this Pull Request?

This sample describes a SPFX application which implement an image gallery with taxonomy base filtering and typed search. This application also implement pagination.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Reall nice sample @ejazhussain - would you be available for doing a demo of this in one of the upcoming SPFx community calls... not massively complex web part, but shows quite nicely really important topics for others... like

- PnPjs usage
- PnP control usage
- Fabric control usage
- Panel popup etc.

Works?

**Comment by ejazhussain** [comment]
@VesaJuvonen . Would love do demo and share knowledge with amazing community.

**Comment by VesaJuvonen** [comment]
Hi @ejazhussain, we would have a spot for 28th of March call or then for the next one on the 11th of April. Either one works currently. Let me know what works for you. Thx.

**Comment by ejazhussain** [comment]
@VesaJuvonen Yes 28th March is fine with me. Do send me call detail so i can put in my calendar. 
Looking forward for this.

**Comment by VesaJuvonen** [comment]
Hi @ejazhussain - small change on this unfortunately due to so many pending community demos. I would have a 10-15 min spot for you in the 11th of April - would that work? You can download the recurrent invite for the SPFx community calls and other calls we do from http://aka.ms/sppnp...

**Comment by ejazhussain** [comment]
Yeah sure. 11th April should be fine with me.

Regards
Ejaz Hussain


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by VesaJuvonen** [comment]
Let's confirm that then. Thanks for volunteering @ejazhussain.

**Pull request merged**
