### PR TITLE
SPFX Tour sample WebPart - react-tour-pnpjs

### PR DESCRIPTION
**Pull request by fredupstair**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                         |
| Related issues? | no |

## What's in this Pull Request?

A SPFx WebPart using PnP/PnPjs, @pnp/spfx-property-controls and ReactTourJS. It allows to create a configurable tutorial/tour of a SharePoint modern page for adoption scope.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Really cool setup and great technical demo even though is highly dependent on the DOM structure... which means that it can get broken at some point... would you be interested on doing a live demo of this in any of the upcoming community calls?

**Comment by fredupstair** [comment]
Hi @VesaJuvonen ,
thank you :) Surely there is a dependency on the DOM, and this is a problem. I tried to limit it, thanks to the use of PnPJS. It would be nice if a reference to the CanvasControl DOM could be taken from PnPJS, so it would be wrapped :)
Anyway, thanks for the demo proposal, I'm available, let me know.
Federico

**Comment by VesaJuvonen** [comment]
Thanks @fredupstair - we would have free spots on the following calls - your call. Let's combine the discussion on the both demos... if that works for you. I'd recommend to keep them completely as a separate ones, so that we can isolate them as own videos.

Free demo spots currently:

- 19th of December
- 2nd of January
- 16th of January 
- 30th of January

You can do one demo in one and then select other call for the next ones... would be recommend for getting maximum visibility for your work.

**Comment by fredupstair** [comment]
Hi @VesaJuvonen 
thanks! If it's okay we can do this
- 19th December react-tour-pnpjs
- 16th January  react-admin-sc-catalog-pnpjs
thanks again for the opportunity :)
Federico

**Comment by VesaJuvonen** [comment]
Deal - thanks for volunteering. You'll see the agenda promos going out few days before the event. If there's any changes on your availability, please send direct email to me... first.last at microsoft.com. Thx.

**Pull request merged**
