### PR TITLE
react-admin-sc-catalog-pnpjs - Site Collection App Catalogs Summary View

### PR DESCRIPTION
**Pull request by fredupstair**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no |
| New sample?     | yes                               |
| Related issues? |  no|

## What's in this Pull Request?
A SPFx WebPart using @pnp/sp/appcatalog and @pnp/spfx-controls-react. It allows to see in a single view all the SiteCollection catalogs and the Apps installed with some useful metadata.

### CODE REVIEW

**Comment by Phuongdinh1981** [comment]
ung dung  rat hay va tot cho android

**Comment by Phuongdinh1981** [comment]
android cua toi rat can

**Comment by VesaJuvonen** [comment]
Another really cool one, which is highly beneficial as well. Would you be interested on doing a live demo of this one as well?

**Comment by fredupstair** [comment]
Hi @VesaJuvonen ,
thanks again! Also for this, I am here, if possible we can put away from the other.
Cheers,
Federico

**Pull request merged**
