### PR TITLE
Upgraded to SPFx 1.6.0 & made bug fix

### PR DESCRIPTION
**Pull request by msekkappan**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no - yes?        Yes                      |
| New feature?    | no - yes?            Yes                   |
| New sample?     | no - yes?                               |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?

Upgraded to SPFx 1.6.0 & made bug fix

### CODE REVIEW

**Comment by msekkappan** [comment]
Upgraded to SPFx 1.6.0 & made bug fix

**Comment by VesaJuvonen** [comment]
thx @msekkappan, appreciated.

**Comment by cheynen** [comment]
This works beautifully in the workbench.  But what do I need to do to deploy it to my tenant?  I must need to modify some code for it to find my CDN?  Etc.?

**Comment by cheynen** [comment]
Thank you… I had done all this and was at a loss.

 

I re ran the steps this time and it worked.  I can’t think of anything I did differently… Or…well, maybe….

 

The only thing I changed was that I had not capitalized the CDN in the code where I changed the cdnBasePath… So, before it was https://kornferry.sharepoint.com/cdn and when I created the CDN I had used capital letters.  When I changed the cdnBasePath to be https://kornferry.sharepoint.com/CDN... It worked… 

 

Can this be possible???

**Pull request merged**
