### PR TITLE
Page Sections Navigation

### PR DESCRIPTION
**Pull request by AJIXuMuK**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | no |

## What's in this Pull Request?

Sample web parts allowing to add sections navigation to the SharePoint page based on Dynamic Data concepts.

page-nav

### CODE REVIEW

**Comment by clohigh** [comment]
Great stuff! @AJIXuMuK

**Comment by VesaJuvonen** [comment]
Thx Alex, this is a quite cool setup and would have numerous discussion points for the community call... would you be interested in doing a live demo in one of the upcoming ones?

**Comment by AJIXuMuK** [comment]
Thanks Vesa!
Yes, of course! Next Tuesday (March 12) would be ideal because of the daylight time :)
But most probably you already have planned demos. 
I’ll look into what other options I have...

**Comment by VesaJuvonen** [comment]
Hi - yes - tomorrow is already locked from agenda perspective. We would have a spot for 28th of March call or then for the next one on the 11th of April. Either one works currently. Let me know what works for you. Thx.

**Comment by AJIXuMuK** [comment]
Hi @VesaJuvonen!
Thank you for the dates! 
Let's do it on March 28.

**Comment by VesaJuvonen** [comment]
That's it then - you'll have a spot in 28th of March. Thanks for volunteering.

**Pull request merged**
