### PR TITLE
Added new sample - react-functional-component to demonstrate simplified hello world sample using a stateless functional component in React

### PR DESCRIPTION
**Pull request by SPDoctor**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    |  no                              |
| New sample?     | yes                               |
| Related issues? | none |

## React Functional Component web part

The purpose of this web part is to make it easier to understand for new developers building their first SPFx web part, when teaching the SharePoint Framework, and to introduce React Functional Components. The web part is a refactoring of the HelloWorld web part that is created by the **@microsoft/generator-sharepoint** Yeoman generator. The resulting rendered web part should look exactly the same, but the complexity of the code has been significantly reduced, and should be much easier to understand for a newcomer to the framework.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi @SPDoctor, great stuff, but there's few things to fix on this PR / or fix and submit a new one before we can merge this.

- Your PR contains also changes to other samples - to GitHub badge sample... would double check what's getting submitted and clean those up
- Your readme does not use the readme template which is required for all of the samples. You have great documentation there, but some key areas are missing - like author information etc. Please check examples from the other samples or move the content simply to the readme template found from https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/README-template.md

Whenever these small things are fixed, happy to take this into the repository and would love to schedule a live demo in the community call for this one.

**Comment by SPDoctor** [comment]
Not sure how it picked up the other commits. I will clean this up and fix the readme (sorry, missed the template). Might take a couple of days as I am travelling tomorrow. Very happy to do a demo on community call.

**Comment by VesaJuvonen** [comment]
Let's get you queued up for next possible SPFx community call for this... which would be 1st of August - if you are available then.

**Comment by SPDoctor** [comment]
Can't do August 1st - maybe the one after or June maybe?

**Comment by VesaJuvonen** [comment]
Last SPFx call in June is fully booked with 3 demos already, so can't get you there... but then next one in August would work?

**Comment by SPDoctor** [comment]
I've put August 15th in my diary.

**Comment by VesaJuvonen** [comment]
thx Bill, that's then settled... adding it to our tracking. Let me know if there's any changes on your availability, if needed.

**Comment by SPDoctor** [comment]
New PR https://github.com/SharePoint/sp-dev-fx-webparts/pull/885 submitted.

My reading of instructions is to branch from **master** but target **dev**. I think this is what resulted in extra commits in the resulting PR. Did I miss something or should I raise this as an issue against the contributor guidance?

**Comment by VesaJuvonen** [comment]
I'll close this one as the changes are in the different PRs. Thx Bill.

**Comment by VesaJuvonen** [comment]
Just a reminder - You have a spot to demo this in August 15th community call - which is tomorrow.

**Pull request closed without merging**
