### PR TITLE
Gdev

### PR DESCRIPTION
**Pull request by siddharth-vaghasia**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                           |
| New feature?    | no                                |
| New sample?     | yes                               |

## What's in this Pull Request?

This is sample webpart which showcase how to implement Google reCaptcha v2 in SPFx. CAPTCHA is used to prevent bots from automatically submitting forms with SPAM or other unwanted content. If we are building a custom input form to get feedback, newsletter subscription or contact us form using SPFx webpart. We might have to implement SPAM protection using some CAPTCHA resolving technique. This sample can come in handy to extend it for your business requirement if you need to implement CAPTCHA in SPFx webpart.

### CODE REVIEW

**Comment by siddharth-vaghasia** [comment]
Hey @LauraKokkarinen ....hope you had good time at MSignite :).... just wanted to check if you got a chance to look at this PR?

**Comment by siddharth-vaghasia** [comment]
@LauraKokkarinen ....can you please advise if get chance to look at this PR ? Please advise if it needs any modification..!

**Comment by LauraKokkarinen** [comment]
Hi @siddharth-vaghasia ,

Thank you so much for contributing this sample! And sorry that it took me so long to get around to it. Things tend to get busy towards the end of the year, and all volunteer-work like approving these PRs quickly gets pushed down the priority list.

Keep up the good work and happy holidays!

Laura

**Comment by siddharth-vaghasia** [comment]
@LauraKokkarinen ....thanks for approving..I can see on twitter you had busy months.....totally understandable.....

Happy holidays...!!!!

**Pull request merged**
