### PR TITLE
Added sample project with API secured with AAD

### PR DESCRIPTION
**Pull request by waldekmastykarz**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | n/a

#### What's in this Pull Request?

- added sample project with API secured with AAD
- moved web part to a subdirectory

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Waldek, appreciated.

**Comment by darrenparkinson** [comment]
Hi.  Thanks for this sample, very useful.  One quick question I have though is how to identify the user from the request, specifically in a node.js api -- could you possibly add a node.js example api to the sample showing how this is done?  Thanks again.

**Comment by waldekmastykarz** [comment]
@darrenparkinson You should be able to get the user name from `req.headers['x-ms-client-principal-name']`

**Comment by darrenparkinson** [comment]
Thanks @waldekmastykarz -- I found that yesterday as it happens when I took another look. Given that headers could be manipulated, is this secure enough to use for authorisation? Or should I be validating the token somehow? Thanks again for the response.

**Comment by waldekmastykarz** [comment]
Ideally you would get the identity from the token. Not sure if you have to validate it yourself again, as it's already been verified during authorization.

**Pull request merged**
