### PR TITLE
Adding the riot-list sample webpart

### PR DESCRIPTION
**Pull request by sebastienlevert**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | N/A

#### What's in this Pull Request?

Adding a sample SharePoint Framework webpart using RiotJS as its templating / component framework.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Sebastien, great contribution.

**Comment by hugoabernier** [comment]
✅ PR affects only one sample file.
❌ Sample is not named correctly.
❌ PR does not contain a `.nvmrc` file.
✅ Sample contains a `README.md` file.
✅ `README.md` contains a visitor stat tracking image.

**Comment by hugoabernier** [comment]
Sample PR validation.
Sample PR validation.

Validation|Status
---|---
## ⚠️ Validation status: warnings
|[Pull request affects only one folder](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#typos-issues-bugs-and-contributions)|✅ Succeeded|
|[Sample folder name](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#sample-folder)|⚠️ Warning|
|[README.md](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#readmemd)|✅ Succeeded|
|[Visitor stat image in README.md](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#visitor-stats-image)|✅ Succeeded|
|[.nvmrc` file](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#nvmrc)|⚠️ Warning|

**Comment by hugoabernier** [comment]
> This message is an experimental message. Please ignore.
Sample PR validation.
Sample PR validation.

Validation|Status
---|---
## ⚠️ Validation status: warnings
|[Pull request affects only one folder](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#typos-issues-bugs-and-contributions)|✅ Succeeded|
|[Sample folder name](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#sample-folder)|⚠️ Warning|
|[README.md](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#readmemd)|✅ Succeeded|
|[Visitor stat image in README.md](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#visitor-stats-image)|✅ Succeeded|
|[Screenshot .PNG in the `assets` folder](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#assets)|⚠️ Warning|
|[.nvmrc` file](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#nvmrc)|⚠️ Warning|

Please address the above issues and push new changes to this branch.
For more information, see the [contributing guidelines](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md).

**Comment by hugoabernier** [comment]
> This message is an experimental message. Please ignore.
Sample PR validation.
Sample PR validation.

Validation|Status
---|---
## ⚠️ Validation status: warnings
|[Pull request affects only one folder](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#typos-issues-bugs-and-contributions)|✅ Succeeded|
|[Sample folder name](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#sample-folder)|⚠️ Warning|
|[README.md](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#readmemd)|✅ Succeeded|
|[Visitor stat image in README.md](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#visitor-stats-image)|✅ Succeeded|
|[Screenshot .PNG in the `assets` folder](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#assets)|⚠️ Warning|
|[.nvmrc` file](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md#nvmrc)|⚠️ Warning|

Please address the above issues and push new changes to this branch.
For more information, see the [contributing guidelines](https://github.com/pnp/sp-dev-fx-webparts/blob/main/CONTRIBUTING.md).

**Pull request merged**
