### PR TITLE
Sample web part for Taxonomy Picker control

### PR DESCRIPTION
**Pull request by jquintozamora**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes

#### What's in this Pull Request?

Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
New Sample Web part for illustrating [Taxonomy Picker control](https://www.npmjs.com/package/react-taxonomypicker).
- Use React for using react-taxonomypicker control inside a custom property pane (it can be used in the webpart itself too).
- Use TypeScript to create the custom property pane control containing the taxonomy picker control.
- Retrieve Terms from a Term Set by Term Set GUID.
- Sync / Async modes configurable via termSetCountMaxSwapToAsync property
- It Uses and depends on SP.Taxonomy.js
- It uses Promise (polyfill it if needed IE)

### CODE REVIEW

**Comment by luismanez** [comment]
Awesome stuff !! will be merged for sure. Thanks for sharing it!

**Comment by VesaJuvonen** [comment]
Hi José ,
sorry for the delay on getting this merged. Looking really nice and thx for getting it shared.

**Comment by jquintozamora** [comment]
Thank you @VesaJuvonen !!
Happy to contribute :)

**Comment by VesaJuvonen** [comment]
Hi José,
would you be available for demonstrating this sample in the next week's monthly community call? - Call is on Tuesday 11th of April at 4 PM GMT (London time). This would be 10-15 walk-through of the sample and code.

**Comment by jquintozamora** [comment]
Hi @VesaJuvonen , 
Thanks! Sure I'd like to.
Please, Let me know if you need further info from me before the meeting. 

Cheers!

**Pull request merged**
