### PR TITLE
Updated to drop 1.4, fixed property pane issues, and added more settings

### PR DESCRIPTION
**Pull request by wobba**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes

#### What's in this Pull Request?

* Made query template optional
* Added more managed properties by default for image previews
* Moved default web part values to the web part definition instead of hardcoded
* Trigger re-rendering of results for all property changes
* Updated to SPFx drop 1.4
* Made the web part bundle assets in the part as per drop 1.4
* Added options to hide/show the file icon in the result card
* Added options to hide/show the created date in the result card
* Hide the filter control if no refiners are specified for the web part
* Code formatting (re-nice)

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx Mikael, based on the chat with you and @FranckyC in Twitter, we should be good to go with this one.

**Comment by FranckyC** [comment]
Yep, thanks @VesaJuvonen!

**Comment by wobba** [comment]
@VesaJuvonen you have eyes and ears everywhere :)

**Comment by wobba** [comment]
@FranckyC I seem to have an issue testing the web part in IE/Edge. I get a load error, both in local workbench, hosted workbench and if deployed. It works just fine in Chrome.

Have you seen this @VesaJuvonen or have input on how to troubleshoot?

Error is:

```
[SPLoaderError.loadComponentError]:

***Failed to load component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchWebPart).

Original error: ***Failed to load entry point from component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchWebPart).

Original error: Error loading https://component-id.invalid/42ad2740-3c60-49cf-971a-c44e33511b93_0.0.1
	Unable to get property 'operation' of undefined or null reference



***INNERERROR:

***Failed to load entry point from component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchWebPart).

Original error: Error loading https://component-id.invalid/42ad2740-3c60-49cf-971a-c44e33511b93_0.0.1
	Unable to get property 'operation' of undefined or null reference

***CALLSTACK:

Error
   at SPError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:10183:9)
   at SPLoaderError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:4211:9)
   at ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3821:9)
   at ErrorBuilder.buildLoadComponentError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3743:9)
   at Anonymous function (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:7952:9)
```

**Comment by wobba** [comment]
@VesaJuvonen I get random errors in IE/Edge with this web part - and not sure why.

Repro:
* gulp serve the sample in a local workbench
* keep hitting refresh (F5) in the browser and you will eventually see this error
* (you can also edit the webpart and add * as the query before refreshing)

When I packed this up and deployed, it failed 100% of the time on IE/Edge.

```
SPLoaderError.loadComponentError]:

***Failed to load component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchWebPart).

Original error: ***Failed to load entry point from component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchWebPart).

Original error: Error loading https://component-id.invalid/42ad2740-3c60-49cf-971a-c44e33511b93_0.0.1
	Unable to get property 'operation' of undefined or null reference



***INNERERROR:

***Failed to load entry point from component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchWebPart).

Original error: Error loading https://component-id.invalid/42ad2740-3c60-49cf-971a-c44e33511b93_0.0.1
	Unable to get property 'operation' of undefined or null reference

***CALLSTACK:

Error
   at SPError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:10183:9)

```

**Comment by wobba** [comment]
@VesaJuvonen @FranckyC 
Added a bug for this in https://github.com/SharePoint/sp-dev-docs/issues/1204 as I cannot see anything weird with the web part it self. So seems SPFx related - perhaps webpack/timing issue.

I get the same error with the initial sample on drop 1.3.

**Pull request merged**
