### PR TITLE
File Upload using AngularJs

### PR DESCRIPTION
**Pull request by dipongkor**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      |  yes
| Related issues?  | n/a

#### What's in this Pull Request?

Sample code added for uploading file using AngularJs 1.x.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Atish for this. Really nice work and demonstrates multiple useful things in Angular side.

**Comment by dipongkor** [comment]
Can I help more in any webcast?

**Comment by VesaJuvonen** [comment]
Sorry for the delay related on the comment around web cast. We do have our monthly community call next Tuesday 13th of Dec at 8 AM PST and if you have availability, we could do 10-15 min spot for quick demo on this call for this. This is also getting recorded and shared in the PnP YouTube channel.

**Comment by dipongkor** [comment]
I can join. Please let me know how can I join.

**Comment by VesaJuvonen** [comment]
Great. These are the monthly calls, which are mentioned in the PnP site at - https://dev.office.com/patterns-and-practices. Direct recurrent download is http://aka.ms/OfficeDevPnPCall. We'll go through first latest changes in the PnP/SharePoint side during past month and then move to demo section. There will be 2-3 demos and we'll need to keep the whole time in one hour, so there won't be massive amount of time for the demo. You'd do the demo with microphone and screen sharing from your machine.

**Pull request merged**
