### PR TITLE
Sample Web Part illustrating how to create dependent properties in We…

### PR DESCRIPTION
**Pull request by AJIXuMuK**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | no

#### What's in this Pull Request?

Sample Web Part illustrating

* requesting Lists and Views data from SharePoint REST API
* creating Knockout dropdown custom component with Fabric UI styling
* creating dependent properties (dropdowns) in Client-Side Web Part Property Pane

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Alex, we'll have a look on this in upcoming days. Looks really nice after initial glance.

**Comment by VesaJuvonen** [comment]
Sorry for the delay Alex, we'll start processing these more detailed next week (24th of Oct forward)

**Comment by VesaJuvonen** [comment]
thx Alex, good to have few knockout samples as well, so thx for this. Worked out nicely.

**Comment by AJIXuMuK** [comment]
Hi Vesa,
 
I saw a November 2016 release on dev.office.com and my name there.
It’s so great to be part of the community!
 
But I have few questions on that and don’t know to whom to write so decided to send email to you as a rock-star of PnP :)
 
Could you please change my first name from Aliaxei to Alex to be more simple? :)
Also is it possible to add link to my GitHub profile? [AJIXuMuK](https://github.com/AJIXuMuK)
And also is it possible to add a name and a logo of a company I’m working in? It’s Sharepointalist and the URL to the logo is [Sharepointalist](http://www.sharepointalist.com/SiteAssets/logo.jpg)
 
I really appreciate your help!

**Comment by VesaJuvonen** [comment]
Absolutely - there was challenge in GitHub UIs around the history tracking, so it only showed a name, but no links to your profile. I just updated the blog post - thx for the note and suggestions. Feel free to send similar things in future as well. We absolutely want to recognize field people who share their knowledge between other community members.

**Pull request merged**
