### PR TITLE
spfx webpart to Tag Teams using a TermSet in SP

### PR DESCRIPTION
**Pull request by luismanez**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                         |
| New feature?    | no                             |
| New sample?     | yes                               |
| Related issues? 

## What's in this Pull Request?
New sample showing how to read and update a custom Schema extension in MS Graph to Tag a Team using metadata from a specific TermSet in SharePoint. The user can select different Terms (up to 3), and are saved as a custom Schema extension in Group Graph entity. Besides, the webpart allows to find other Teams tagged wit the same Tag (for demo puposes only 1st Tag is used to run the query)

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
This is really really really interesting stuff, so thanks for sharing it. Would you be interested in doing a community call demo on this one? Would be a great story to get recorded for others. This could be actually demonstrated in both calls as it's not really about SPFx, it's more about demonstrating the usage of custom schema extensions in the context of SharePoint and Microsoft Teams.

**Comment by VesaJuvonen** [comment]
A small thing also - Readme was missing the tracking image on the end, so will add that there.

**Comment by luismanez** [comment]
Thanks Vesa! happy to show it in a community call, sure. Let me know the possible dates.
Thanks for fixing the Readme file!

**Comment by VesaJuvonen** [comment]
Hi @luismanez - sorry for not following up on that demo offer, luckily noticed... just too many emails from GitHub. We would have still spots for next week's SPFx call on 23rd of May or then later either on 6th of June or 20th of June. Let me know based on your availability. Thx.

**Comment by luismanez** [comment]
Hi @VesaJuvonen, yeah, no worries, was during MS Build, so I thought that. 6th of June works fine for me. Let´s block that slot :). Thanks!

**Comment by VesaJuvonen** [comment]
Thx @luismanez - I've added you on the agenda for 6th of June. Thanks for doing the demo advance.

**Pull request merged**
