### PR TITLE
react-personal-greeting

### PR DESCRIPTION
**Pull request by zachroberts8668**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | no |

## What's in this Pull Request?

Adding a new sample web part to that provides a way to display a greeting to the current user.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Thanks @zachroberts8668 for the cool sample!

**Comment by hugoabernier** [comment]
Hey @zachroberts8668 would you be interested in demoing this web part on an upcoming community call? We have an opening on May 21st or June 4th!

**Comment by zachroberts8668** [comment]
> Hey @zachroberts8668 would you be interested in demoing this web part on an upcoming community call? We have an opening on May 21st or June 4th!

Hi @hugoabernier , I would be happy to demo this web part! I can do the demo on 5/21 if it is still open 😊

**Comment by hugoabernier** [comment]
Perfect @zachroberts8668 ! I have you on the May 21st PnP call. Looking forward to your demo!

**Comment by zachroberts8668** [comment]
Hi Hugo,

Sorry for the late notice but I will not be able to make it to the PnP call
on Thursday 5/21. I would still like to do a demo for the community if 6/4
is still available I can do that or a different date.

Thanks,
Zach

**Pull request merged**
