### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by russgove**
| Q               | A
| --------------- | ---
| Bug fix?        | no - yes?
| New feature?    | no - yes?
| New sample?      | no - yes?
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Please describe the changes in this PR. Sample description or details around bugs which are being fixed.

#### Guidance
*You can delete this section when you are submitting the pull request.* 
* *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
* *Please target your PR to 'dev' branch.*

Thanks for your contribution! Sharing is caring.

### CODE REVIEW

**Comment by russgove** [comment]
Added property-bag webparts to enable editing of property bags and navigate using them

**Comment by VesaJuvonen** [comment]
Hi Russell,
Looks ok in general, but would ask to use the default readme template available at
https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/README-template.md. We are asking to use this to provide consistency and standard metadata for all of the samples, which are getting published. I'll leave this open for now and you can push that as additional commit or alternative resubmit the sample as new PR. Thx for the requested changes advance.

**Comment by russgove** [comment]
changed readme and  a couple of other fixes

**Comment by VesaJuvonen** [comment]
thx Russell, will fix the tracking image mistake on this (should be on your solution specific folder), but all good. There was also additional .vscode/launch.json file to root of the repo, which will get removed to avoid confusion around this.

**Pull request merged**
