### PR TITLE
Added PowerBI Embedded sample

### PR DESCRIPTION
**Pull request by rolandoldengarm**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      |  yes
| Related issues?  | no

#### What's in this Pull Request?

A sample client-side web part that embeds a PowerBI report PowerBI Embedded.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Roland, we'll have a look on this and will get it merged on the dev branch later today. Looks really good and thx for sharing.

**Comment by VesaJuvonen** [comment]
thx Roland, we would have one ask around this, which is the folder naming for the sample solution. We just updated our contribution guidance with details on this, so sorry for the additional ask, since that was missing when you submitted your sample - https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/.github/CONTRIBUTING.md. 

Key point to notice would be the folder naming. So we should use angular-, react- etc. in the name, so that sample is getting grouped with similar technologies in the folder. If you are not using any generic library, we would ask that folder name starts with js- prefix. So in this case folder name would be "js-powerbi-embedded".

This is really nice sample showing the integration and great to get it included. Hopefully folder rename works for you, but obviously can do that afterwards as well, if you are running out of time.

**Comment by rolandoldengarm** [comment]
@VesaJuvonen No worries at all. I've renamed the folder to js-powerbi-embedded!

**Comment by VesaJuvonen** [comment]
thx Roland, great stuff.

**Pull request merged**
