### PR TITLE
Example of MS Graph Teams beta API usage

### PR DESCRIPTION
**Pull request by AJIXuMuK**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | no |

#### Summary

The web part illustrates usage of MS Graph beta APIs to work with Teams:
* O365 group creation
* Team creation
* Channel creation
* Installation of an app
* Adding tab
* Getting apps from App Catalog

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Alex. We should definitely do a demo on this in one of the upcoming community calls if you are fine with that.

**Comment by AJIXuMuK** [comment]
Hi Vesa,

Will be glad to demo it!

**Comment by AJIXuMuK** [comment]
@VesaJuvonen do you have any specific date? Next dev bi-weekly call is on Thanksgiving. Next date is monthly call.
Just let me know what you think on that.

**Comment by VesaJuvonen** [comment]
sorry for the small delay... We could cover this in 6th of Dec SPFx SIG or in the 11th of Dec monthly call. Both have still free spots for demos if you are available.

**Comment by AJIXuMuK** [comment]
11th works better.
BTW, I added one more PR to move from beta to v1.0 endpoints for Graph: #693

**Comment by VesaJuvonen** [comment]
11th of Dec it is then. Deal. Will get you on the agenda. Thx.

**Pull request merged**
