### PR TITLE
Real Time News Feed using Microsoft Flow, Azure and socket.io

### PR DESCRIPTION
**Pull request by FranckyC**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| New sample? | **yes** |
#### What's in this Pull Request?

An end-to-end sample of a real time news feed web part using different technologies like Microsoft Flow, Azure Service Bus and web sockets through the socket.io library.

The deployment (SharePoint and Azure) is fully automated via PowerShell using the PnP cmdlets and an Azure Resource Manager template.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Franck, we'll get this processed during this week. Looks really interesting and demonstrates nicely slightly more advance scenarios.

**Comment by FranckyC** [comment]
@VesaJuvonen Do you have any update for this sample?

**Comment by VesaJuvonen** [comment]
thx FranckyC on this. Great solution, even though requires some level of configuration, but absolutely worthwhile and shows nicely how to combine different techniques. Would you be available for doing again a demo around this in the next Tuesday's monthly community call? 10-15 minutes spot for showing the capability in practice and key pointers of the code.

**Comment by FranckyC** [comment]
Thks @VesaJuvonen however, I've realised yesterday that I'm could replace Microsoft Flow with an Azure Logic App (which is much more elegant I think) so I will probably update the solution soon. For the demo part, it won't be possible due to the MVP Summit :(

**Comment by VesaJuvonen** [comment]
Good point on the Summit. Will be there as well, but we can't reschedule the call, so all MSFTs will be in the call, while MVPs are in actual summit sessions. No worries on this, we have also other things to show, so all good, even though this would have been a nice demo as well. Let's do that another time. This could be also potential web cast topic, where we have few slides and then live demo as weekly web cast recording, if you are fine with that. We can talk more during next week as well.

**Comment by FranckyC** [comment]
@VesaJuvonen Sure! A webcast could be a good option for this kind of sample. How does it work? Do I have to send you a recorded session?

**Pull request merged**
