### PR TITLE
Added Vue.js todo sample

### PR DESCRIPTION
**Pull request by s-KaiNet**
| Q               | A
| --------------- | ---
| New sample?      | yes

#### What's in this Pull Request?
SPFx meets [Vue.js](https://vuejs.org/v2)! :)      

Sample implementation of Todo web part with Vue.js.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Sergei, we're planning to get these processed in upcoming days. Looks really good and great to have Vue.js sample included as well.

**Comment by Danny-Engelman** [comment]
Just reading code, not forking or executing... (well executing in my twisted brain).. so can't do PRs

``
public addTodo(): void {
    if(!this.todoTitle){
        return;
    }
    this.mytodos.push(this.todoTitle);
    this.todoTitle = '';
}
``

How about:

``
public addTodo(): void {
    if(this.todoTitle){
      this.mytodos.push(this.todoTitle);
      this.todoTitle = '';
    }
}
``

**Comment by s-KaiNet** [comment]
It's just a matter of styling.. I don't like nesting and strongly believe that my approach increases readability.   
But that some kind of holy-war question :). You can read more [here](http://stackoverflow.com/questions/9267643/if-return-vs-if-else-efficiency).

**Comment by Danny-Engelman** [comment]
Okay, my apologies.
I thought the goal was to develop readable example code for those who are not experienced developers

Indeed, there are enough wars

The example your refer to

```
public void SomeFunction(bool someCondition)
{
    if (!someCondition)
        return;
    // Do Something
}
```

is difficult for new learners because they have to understand two concepts:
- the negation concept,
- and there is an implicit return

```
public void SomeFunction(bool someCondition)
{
    if (!someCondition)
        return;
    // Do Something
    return;
}
```

**Comment by s-KaiNet** [comment]
I would say developers without experience in javascript\typescript should not start learning with SFPx, because SPFx actually uses a lot of advanced approaches. ;)  I would say at least basic understanding of js\ts (and webpack ideally) is required to start learning SPFx

Examples I'm referring are not about javacript, these are general programming questions

**Comment by Danny-Engelman** [comment]
See, no war. We totally agree. 

> "Developers without experience in javascript\typescript should not start learning with SPFx"

**Pull request merged**
