### PR TITLE
Sample webpart for opening webcam and capture photo

### PR DESCRIPTION
**Pull request by siddharth-vaghasia**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | No                             |
| New feature?    | No                               |
| New sample?     | Yes                               |
| Related issues? | NA|

## What's in this Pull Request?

This PR is to add a new sample spfx webpart to demonstrate usage of webcam and capturing photo.

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Hi Siddharth!

Thank you for this awesome sample! Great job with both the code and the README file! Always a pleasure to merge PRs like this one. :)

Laura

**Comment by LauraKokkarinen** [comment]
Hi @siddharth-vaghasia ,

Would you like to do a short demo about this sample in one of our future SPFx community calls?

Laura

**Comment by siddharth-vaghasia** [comment]
@LauraKokkarinen ....Sure definitely, would love to...

Thanks
Siddharth

**Comment by LauraKokkarinen** [comment]
@siddharth-vaghasia Great to hear! Would the 7th of November after your vacation work for you?

Laura

**Comment by siddharth-vaghasia** [comment]
Yes...7th of Nov works for me..

Thanks
Siddharth

**Comment by LauraKokkarinen** [comment]
@siddharth-vaghasia Great to hear! I've marked a 10-15 min slot for your demo on the 7th. Cheers! :)

Laura

**Comment by siddharth-vaghasia** [comment]
Thanks..!!!

**Comment by LauraKokkarinen** [comment]
Hi @siddharth-vaghasia 

I'm so sorry but I'll have to postpone your demo until a later date -- if you are still happy to do it later. It was just decided that we'll do some kind of an "Ignite special" call on the 7th of November and will not have any demos on that community call. I'm so sorry about this as we had already agreed on that date. Would you be ok doing your demo, e.g., on the 21st of November instead?

Laura

**Comment by siddharth-vaghasia** [comment]
@LauraKokkarinen ...

That's fine, totally understandable... no need to be sorry.. yes i would  be available 21st of Nov... In fact, it would be good. I am right now working on upgraded version of same sample with some advance feature like uploading photo to SharePoint library...   

Thanks
Siddharth

**Comment by LauraKokkarinen** [comment]
@siddharth-vaghasia The 21st it is then! :)

Laura

**Comment by siddharth-vaghasia** [comment]
@LauraKokkarinen ..just confirming my slot on demo...

**Pull request merged**
