### PR TITLE
React Modern Charts

### PR DESCRIPTION
**Pull request by jcoleman-pcprofessional**
| Q               | A
| --------------- | ---
| New sample?      |  yes

#### What's in this Pull Request?

New sample, React Modern Charts: Chart.JS based web parts with data sourced from any SharePoint list in a web application

Thanks for your contribution! Sharing is caring.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Excellent Jeremy, appreciated.

**Comment by VesaJuvonen** [comment]
Hi Jeremy,
would you be available for demonstrating these modern calendar and chart web parts in April monthly community call next Tuesday? - Call is on 8 AM PT and we would have 10-15 min for showing the samples and key elements from the code. Sounds good?

**Comment by jcoleman-pcprofessional** [comment]
Hi Vesa,
I'd be more than happy to do this.  Thanks for the offer.

**Comment by VesaJuvonen** [comment]
thx Jeremy, you can download recurrent invite to the call from http://aka.ms/sppnp-call, unless you have done that in the past already. This is the monthly community open for anyone to drop by and to see what we are doing. Next Tuesday we'll start with 15 min summary on April release and then we have 3 demos... and you'll be one of them, meaning that you have max 15 min to quickly show what's being built and how. That's not much time, so showing functionality and then few key pointers from the code is really the right approach. I'll update you on the agenda, which goes live with monthly release notes on Monday (at http://dev.office.com/blogs)

I won't be unfortunately personally joining on this call, since will be on family vacation. Other PnP core team members however are up to date on the plan and they'll update you as the presenter etc. I'll check the recording when back in business.

Thx for volunteering and looking forward to see this. Thx also for sharing the samples and your knowledge for the benefit of others.

**Pull request merged**
