### PR TITLE
Sample react-mobx

### PR DESCRIPTION
**Pull request by kmees**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| New sample? | **yes** |
| Related issues? | none |
#### What's in this Pull Request?

Sample webpart implementation using React & [Mobx](https://github.com/mobxjs/mobx) for state management as discussed in latest jssig

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Kevin, we'll get these reviewed hopefully fast. We need these kind of "stepping-stones" for showing basic patterns anyway, before we can concentrate on more complex scenarios.

**Comment by kmees** [comment]
@VesaJuvonen if you want to do a webcast or a talk in the JSSIG regarding state management or some other basic react stuff I'd be happy to talk about it.

**Comment by VesaJuvonen** [comment]
Hi Kevin, doing the Redux and Mobx demos in this weeks SPFX SIG would be great, if you can commit on those. That would be great add-on value for the call and we are looking for community members to demonstrate these things anyway. Happy to book you a spot for the Thursday's call for 20 min, if that works for you?

**Comment by kmees** [comment]
sure, can do

**Comment by VesaJuvonen** [comment]
thx Kevin, based on this, we'll get you that 20 minutes for Thursday to demo these two through. Thanks for this advance.

**Pull request merged**
