### PR TITLE
Adds SPFx react slide swiper sample

### PR DESCRIPTION
**Pull request by VelinGeorgiev**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Adds SPFx React web part sample that demonstrates mobile touch slide swiper based on a popular feature rich JavaScript library called Swiper.

Please see the README file for more information or let me know if any questions.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx Velin,
simple and clean stuff. We are looking for potential presenters still for tomorrow's SIG call - would you be available for quick demo? - around 3 PM GMT / 7 AM PT.

**Comment by VelinGeorgiev** [comment]
Hi Vesa (@VesaJuvonen), I will be available for a demo and will join tomorrow.

**Comment by VesaJuvonen** [comment]
Excellent - let's dot hat then. We'll organize a spot for your for tomorrow's call. Thx for the commitment and demo advance. Always appreciated.

Ping @patrick-rodgers as FYI.

**Comment by VelinGeorgiev** [comment]
@VesaJuvonen seems that this pull request has been merged into `master` directly instead of `dev` first. That is probably my mistake, selecting the wrong branch to merge with. 

- I created another pull request https://github.com/SharePoint/sp-dev-fx-webparts/pull/418 that merges `master` into `dev` to bring that sample in the `dev` branch.

Sorry for the troubles caused.

**Comment by VesaJuvonen** [comment]
uups... all good. I'll rather do a cross merge between and delete the new PR... just to make them 100% sync'd... I should have noticed as well.

**Pull request merged**
