### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by russgove**
| Q               | A
| --------------- | ---
| Bug fix?        no ?
| New feature?    no?
| New sample?     |yes?

#### What's in this Pull Request?

Add new sample react-securitygrid.

### CODE REVIEW

**Comment by russgove** [comment]
Added fabric icons and styling

**Comment by VesaJuvonen** [comment]
Reall cool stuff, thx Russell, appreciated.

**Comment by VesaJuvonen** [comment]
Would you mind doing a demo on this in the 7th of Dec SIG call? - cool implementation.

**Comment by russgove** [comment]
i can do that. can you help me get an answer on this, so i can make it work with ad groups: 
https://sharepoint.stackexchange.com/questions/230700/how-do-i-get-to-an-azuread-group-members-from-a-sharepoint-loginname-using-the-g?newsletter=1&nlcode=161400%7cff79

**Comment by VesaJuvonen** [comment]
Thanks Russ for the volunteering, looking forward to seeing this live. I'll see what I can do with the group information handling, but might be hard to get this resolved by Thursday - it's though also good discussion point during the demo to see if someone from the community can solve or provide also details around your question.

**Pull request merged**
